### ISSUE TITLE
 API.modifyPickerConfig not honoring format config/ not populating entity picker:client

### ISSUE THREAD

**Issue by fayranne** [bullhorn/novo-elements#1032]
**Describe the bug**
API.modifyPickerConfig does not appear to be honoring the formatting passed in the original controller causing items to be seen as [Object object]

modifyPickerConfig is not returning picker:client results

**To Reproduce**
Cannot reproduce the first scenario as the code was rolled back.

**Expected behavior**
Picker populates as expected (formatting and items correctly displayed)

**Actual behavior**
A clear and concise description of the behavior caused by this bug.

**Specifications**
  - Version: 3.11 (broke multiple versions prior however)

**Comment by michael-amaya-bh** [comment]
Closing, as this is a stale issue. Can re-submit if this issue still persists
