### ISSUE TITLE
expose sanitize on displayTip function

### ISSUE THREAD

**Issue by MacChad** [bullhorn/novo-elements#1041]
![displayTip-html](https://user-images.githubusercontent.com/60210/64366825-0fbcc280-cfe5-11e9-96fd-4ca65afcec9b.png)
**Describe the solution you'd like**
The novo-elements documentation (https://bullhorn.github.io/novo-elements/#/utils/tip-well) describes a tip-well that allows for html formatting but it appears this feature isn't exposed in the API.displayTip function. I believe it's related to `sanitize`

**Will this feature require a breaking change?**
Does your feature request require breaking changes to existing functionality of current components or services?
- [ ] Yes
- [X] No
- [ ] Not sure

**Alternative solutions**
I've not come up with any alternatives.

**Will this feature require a change to dependencies?**
API.displayTip ???

**Additional context**
Clients used to be able to use html in description and hint text, but now we sanitize that html out.

**Comment by MacChad** [comment]
specific file needing the change: https://github.com/bullhorn/novo-elements/blob/master/projects/novo-elements/src/elements/tip-well/TipWell.ts

**Comment by MichaelDill** [comment]
This issue looks to have been fixed with the above commits. Closing.
