### ISSUE TITLE
Novo-Select clear does not deactive last selected

### ISSUE THREAD

**Issue by ZacharyJorn** [bullhorn/novo-elements#1049]
**Describe the bug**
If clearing a novo-select using .clear the last selected option in the novo-select will have a check next to it. The selected.active is still true for the last selected option. This a visual bug only. Visually the option in the drop down is still selected (the option has a check next to it in the list).

**To Reproduce**
1. Select an option in a novo-select
2. Use .clear to clear the selected option
3. Open up the novo-select

**Expected behavior**
Nothing in the dropdown is selected

**Actual behavior**
The last selected option in the dropdown is still selected (visually)

**Screenshots**
![Novo-selectBug](https://user-images.githubusercontent.com/44657047/66765043-ac8a3f80-ee70-11e9-97b2-899c0d8968fc.PNG)

**Additional context**

**Comment by MichaelDill** [comment]
@ZacharyJorn Can you update the description for this bug? I think you have the expected and actual behavior reversed. Also if you could throw together a demo for this, that would be helpful.
Template: https://stackblitz.com/edit/bullhorn-angular-starter-template?file=index.html

**Comment by ZacharyJorn** [comment]
My apologies I had the expected and actual behaviors swapped. Those are fixed now and I can work on getting a demo put together.

**Comment by ZacharyJorn** [comment]
Having issues reproducing on stackblitz. Will upload a video and code.

**Comment by ZacharyJorn** [comment]
`    this.profileCreated.emit();
    this.profileSelect.selected.active = false;
    this.profileSelect.clear();`

**Comment by ZacharyJorn** [comment]
This fixes the above issue
`   this.profileSelect.selected.active = false;
    this.profileSelect.clear();`
