### ISSUE TITLE
Form groups in Firefox

### ISSUE THREAD

**Issue by ZacharyJorn** [bullhorn/novo-elements#1055]
**Describe the bug**
In firefox, form groups overflow onto the next control

**To Reproduce**
Create a from group with some controls that include at least 1 textbox (type number) and a checkbox.

**Expected behavior**
Form group controls display one after the other without overlapping

**Actual behavior**
Some of the form group controls will overlay onto each other

**Specifications**
Firefox browser only

**Screenshots**
This is what it looks like in chrome.
![chrome_novo_elements_bug](https://user-images.githubusercontent.com/44657047/69062029-e99da080-09df-11ea-8c43-9c6943b848dd.PNG)

This is what it looks in firefox.
![firefox_novo_bug](https://user-images.githubusercontent.com/44657047/69062004-dd194800-09df-11ea-81ad-8e5f70d6dc5c.PNG)

**Comment by MichaelDill** [comment]
Easy to repro by visiting demo page http://bullhorn.github.io/novo-elements/#/form-controls/form-groups in firefox.
