### ISSUE TITLE
[Forms] - OptionsUrl http.get is not a function

### ISSUE THREAD

**Issue by rnitu** [bullhorn/novo-elements#1070]
**Describe the bug**
I get the jobOrder meta via REST API and pass along data to formUtils.toFieldSets. The forms looks great, but when I try a picker that has an 'optionsURL', options do not get populated. 

Console shows error: _'TypeError: http.get is not a function.'_

Am I doing anything wrong?

From what I can tell looks like the component housing getOptionsConfig() needs to be updated to use HttpClient.

```
        // JobOrder
        this.dynamicJobOrder = this.formUtils.toFieldSets(this.jobForm, '$ USD', {}, { token: 'TOKEN', military: true });
        this.formUtils.forceShowAllControlsInFieldsets(this.dynamicJobOrder);

        this.formUtils.setInitialValuesFieldsets(this.dynamicJobOrder, ' ');
        this.dynamicFormJobOrder = this.formUtils.toFormGroupFromFieldset(this.dynamicJobOrder);
```

example form picker: 

```
optionsUrl: "https://cls42.bullhornstaffing.com/core/options/Client"
sortOrder: 40
hint: " "
label: "Hiring Manager"
type: "TO_ONE"
systemRequired: false
readOnly: false
hideFromSearch: false
optionsType: "Client"
description: " "
name: "clientContact"
optional: false
inputType: "SELECT"
multiValue: false
required: true
confidential: false
associatedEntity:
entityMetaUrl: "https://cls42.bullhornstaffing.com/core/meta/ClientContact?fields=*"
entity: "ClientContact"
label: "Contact"
dateLastModified: "1580138193587"
fields: Array(3)
0:
dataType: "Integer"
optional: false
name: "id"
type: "ID"
__proto__: Object
1:
sortOrder: 20
hint: ""
label: "Contact Name"
type: "SCALAR"
systemRequired: false
dataType: "String"
readOnly: false
hideFromSearch: false
maxLength: 50
description: ""
name: "firstName"
optional: true
multiValue: false
required: true
confidential: false
__proto__: Object
2:
sortOrder: 30
hint: ""
label: "Contact Name"
type: "SCALAR"
systemRequired: false
dataType: "String"
readOnly: false
hideFromSearch: false
maxLength: 50
description: ""
name: "lastName"
optional: true
multiValue: false
required: true
confidential: false
```
The function with the error:

```
class OptionsService {
    constructor() { }
    /**
     * @param {?} http
     * @param {?} field
     * @param {?} config
     * @return {?}
     */
    getOptionsConfig(http, field, config) {
        return {
            field: 'value',
            format: '$label',
            options: (/**
             * @param {?} query
             * @return {?}
             */
            (query) => {
                return new Promise((/**
                 * @param {?} resolve
                 * @param {?} reject
                 * @return {?}
                 */
                (resolve, reject) => {
                    if (query && query.length) {
                        http.get(`${field.optionsUrl}?filter=${query || ''}`).subscribe(resolve, reject);
                    }
                    else {
                        resolve([]);
                    }
                }));
            }),
        };
    }
}
```

Novo version 4.0.1

**Comment by MichaelDill** [comment]
Hello rnitu,
When you are calling toFieldSets(), that third parameter that you are a passing an empty object to, should be an instance of HttpClient that you pass in. It will then use that instance to make the http.get() calls for the options urls. I hope this helps!

**Comment by rnitu** [comment]
Got it, thank you! This is for a custom component where we use appBridge to make calls from within the context of the logged on user. When I pass this.httpClient the request is made without the rest token, thus unauthorized.  

Is there any way we can use appBridge instead of httpClient, or any idea how to pass the rest token?

Thank you for your help!

**Comment by MichaelDill** [comment]
Ah I understand. We have an example of this in our https://github.com/bullhorn/extension-samples repo. You can override novo-element's options service with your own implementation, and use Appbridge's HttpGet to complete the call instead the passed in http: https://github.com/bullhorn/extension-samples/blob/master/10.CandidateEditTab/src/app/services/extensionOptions.service.ts. I think you could also pass over a wrapped version of Appbridges http,

**Comment by rnitu** [comment]
Got it, perfect! Thank you so much!
