### ISSUE TITLE
Can Field Interactions make a field read-only if populated?

### ISSUE THREAD

**Issue by HTRomano** [bullhorn/novo-elements#1111]
I'm new to JS and FI and wanted to know if Field Interactions can make a field read only if populated.  We want to lock down a contact's company field if it's populated so users aren't moving their contacts to a new company.

**Comment by Thall1982** [comment]
yep, super simple - 

var field = API.getValue(API.getActiveKey());
if(!field)
  {
  API.enable(API.getActiveKey());
  }
else
  {
  API.disable(API.getActiveKey());
  }

use the event 'on blur' and also tick the box for 'run on init'

**Comment by HTRomano** [comment]
This worked like a charm! Thank you so much.  Just curious, what does "on blur" mean?

**Comment by Thall1982** [comment]
blur - triggers when you click away from field
oninit - triggers on load
onchange - triggers on change (essentially every key stroke if a free text field)
focus - triggers when you click on a filed

**Comment by HTRomano** [comment]
This is SO helpful thanks.

**Comment by Thall1982** [comment]
no problem at all, happy to help. There is a whole world of fun you can have with the interactions

**Comment by HTRomano** [comment]
I wish there was an instructions manual!! :-)

**Comment by Thall1982** [comment]
yeah documentation is limited. I started from scratch on it a couple of years ago and we have alot of interactions in play now (too many - 400).

**Comment by HTRomano** [comment]
Well thank you so much for your help! I really appreciate it.
