### ISSUE TITLE
PreSave Page Interaction API.promptUser() not working

### ISSUE THREAD

**Issue by Thall1982** [bullhorn/novo-elements#1134]
Hi, 

we are trying to use the API.promptUser() as a pre save page interaction, the notification pops up but the page then just continues to save and cancels the message prior to the user clicking on OK - which is the way i understand the functionality of this call.

example:
                API.promptUser({
                headerText: 'TO BE READ',
                subheaderText: 'Thank you for reading this prompt, .'
                });

i have tried this on multiple entities with the same issue each time. 

Any ideas? what we are aiming for is a simple prompt that delays the page saving until the user clicks OK on the prompt. Likewise if they click Cancel it then wont save the page.

thanks,

**Comment by alexvdvalk** [comment]
Pre save expects a promise to be returned, so try this:

`return new Promise((resolve) => {
  API.promptUser({
    headerText: "TO BE READ",
    subheaderText: "Thank you for reading this prompt,",
  }).then((result) => {
    if (result === true) {
      console.log("user clicked YES button");
    } else {
        console.log("user clicked cancel button, or close button", API);
    }
    resolve(); // tells bh to continue the save process
  });
});`

In your case it sounds like you may want to cancel the save process if the user clicks the cancel button. I dont think this is possible, so an alternative is to add this code into a field interaction.

**Comment by Thall1982** [comment]
cheers @alexvdvalk - that is now working as expected.

We'll probably hide the Cancel/Yes buttons if possible as they ser4ve no purpose as it saves regardless

**Comment by Thall1982** [comment]
is there a way to wrap text within the subheadertext area:

API.promptUser({
                headerText: "TO BE READ",
                subheaderText: "Line1.\n Line2 \n Line3 ",
            })

Tried the obvious but it is ignored and displays as 1 line and therefore does not display longer text strings
