### ISSUE TITLE
[Table] - Date Options Localization

### ISSUE THREAD

**Issue by jgodi** [bullhorn/novo-elements#116]
The date options inside the Table filters need to be localized.

**Comment by bvkimball** [comment]
Is this still open?

**Comment by jgodi** [comment]
Yes, the were translated in another place. Still need to be in the Table `getDefaultOptions`

**Comment by jgodi** [comment]
Fixed in https://github.com/bullhorn/novo-elements/commit/b41848d5ece06103d4575b95082e62d4380010c6
