### ISSUE TITLE
Novo Table Columns are not typed

### ISSUE THREAD

**Issue by blitzmann** [bullhorn/novo-elements#1167]
**Describe the solution you'd like**
Columns for table are currently typed as `Array<any>`. I'm requesting these to have a proper type. 

https://github.com/bullhorn/novo-elements/blob/9e02750b3a9491a720a3b29846bcb26cae3d5376/projects/novo-elements/src/elements/table/Table.ts#L237

**Will this feature require a breaking change?**
Does your feature request require breaking changes to existing functionality of current components or services?
- [ ] Yes
- [x] No
- [ ] Not sure

**Alternative solutions**
N/A

**Will this feature require a change to dependencies?**
No

**Additional context**
N/A

**Comment by bvkimball** [comment]
Table is deprecated in v6.0.0, we will be replacing it with simple-table in future releases.  It will have better Typing support then.  Please use NovoDataTable instead.
