### ISSUE TITLE
Styling issue with Data Table - Can't see records.

### ISSUE THREAD

**Issue by blitzmann** [bullhorn/novo-elements#1172]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)

**Describe the bug**
Data Tables have a styling issue in which the table is collapsed in a way that hides all the records. This can be seen in the demo here:
https://bullhorn.github.io/novo-elements/#/components/data-table

![image](https://user-images.githubusercontent.com/3904767/112901076-49b35500-90b2-11eb-9cf5-a8aea163aa53.png)

Giving a `min-height: 400px` (for example) to `.novo-data-table-outside-container`  seems to fix it, but this is by no means an actual fix.

![image](https://user-images.githubusercontent.com/3904767/112901257-82532e80-90b2-11eb-9988-15ef0568fbae.png)

Looks like an issue with some element positioning.

**To Reproduce**
1) See demo for "Data Table: Remote data service"

**Specifications**
  - Version: We're using 4.3.6, but problem is present within latest commit as well
  - Platform:
  - Subsystem:

**Comment by michael-amaya-bh** [comment]
This has been fixed. Let us know if you have any questions or concerns.
