### ISSUE TITLE
[Multi-Select Pickers] - "Clear all" functionality

### ISSUE THREAD

**Issue by marycurtis** [bullhorn/novo-elements#120]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)

##### **I'm submitting a [FEATURE REQUEST]**
* Add a "clear all" button on multi-select pickers to clear all chips
* Magnifying glass remains

##### **What is the current behavior?**
The chips can be cleared individually, but there is no way to clear the entire selection.

##### **What is the expected behavior?**
* After selecting at least one item from the dropdown, the "clear all" button appears.
* When the user clicks the button, the previously selected items are removed.
* The button only appears when one or more items has been selected.

##### **What is the motivation / use case for changing the behavior?**
As a user, I want to clear my entire selection without having to remove items one at a time. I also want to understand that I still have the ability to search for additional items. 

![search - clear all](https://cloud.githubusercontent.com/assets/16156795/17117226/36306494-5289-11e6-829f-285a978da56c.png)

**Comment by jgodi** [comment]
@marycurtis Can the magnifying glass turn into an 'X' to clear?

**Comment by marycurtis** [comment]
@jgodi The reason why this one would be different is because you still have the ability to search after you've selected something, so we want to make that clear to the user by keeping the magnifying glass there.
