### ISSUE TITLE
[Multi-Picker] Add departments & users picker 

### ISSUE THREAD

**Issue by yi-ren** [bullhorn/novo-elements#128]
##### **I'm submitting a [FEATURE REQUEST]**

There needs to be a picker where a user can select multiple departments and users at the same time.
##### **What is the current behavior?**

The picker doesn't exist.
##### **Other information**

_(e.g. detailed explanation, screenshots, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)_

UX: https://invis.io/JW850J249

**Comment by jgodi** [comment]
Implemented already :)
