### ISSUE TITLE
Angular imask error

### ISSUE THREAD

**Issue by npramod189** [bullhorn/novo-elements#1285]
I referred GitHub Novo elements docs and added the same versions for all dependencies in my project, I tried to run my application by doing ng serve. But I am facing the below error related to angular-imask

My node version: 14.19.1
Angular version: 10.2.2

ERROR in ./node_modules/angular-imask/fesm2015/angular-imask.mjs 164:239-262
Can't import the named export 'COMPOSITION_BUFFER_MODE' from non EcmaScript module (only default export is available)ERROR in ./node_modules/angular-imask/fesm2015/angular-imask.mjs 187:31-54
Can't import the named export 'COMPOSITION_BUFFER_MODE' from non EcmaScript module (only default export is available)ERROR in ./node_modules/angular-imask/fesm2015/angular-imask.mjs 236:178-190
Can't import the named export 'ElementRef' from non EcmaScript module (only default export is available)ERROR in ./node_modules/angular-imask/fesm2015/angular-imask.mjs 180:24-37
Can't import the named export 'ElementRef' from non EcmaScript module (only default export is available)ERROR in ./node_modules/angular-imask/fesm2015/angular-imask.mjs 34:26-38
Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)ERROR in ./node_modules/angular-imask/fesm2015/angular-imask.mjs 35:28-40
Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)ERROR in ./node_modules/angular-imask/fesm2015/angular-imask.mjs 181:30-36
Can't import the named export 'Inject' from non EcmaScript module (only default export is available)ERROR in ./node_modules/angular-imask/fesm2015/angular-imask.mjs 186:30-36
Can't import the named export 'Inject' from non EcmaScript module (only default export is available)ERROR in ./node_modules/angular-imask/fesm2015/angular-imask.mjs 13:18-28
Can't import the named export 'Injectable' from non EcmaScript module (only default export is available)ERROR in ./node_modules/angular-imask/fesm2015/angular-imask.mjs 229:18-28
Can't import the named export 'Injectable' from non EcmaScript module (only default export is available)ERROR in ./node_modules/angular-imask/fesm2015/angular-imask.mjs 190:22-27
Can't import the named export 'Input' from non EcmaScript module (only default export is available)ERROR in ./node_modules/angular-imask/fesm2015/angular-imask.mjs 192:22-27

ERROR in node_modules/angular-imask/imask-factory.d.ts:5:21 - error TS2694: Namespace '"/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'. 5 static ɵfac: i0.ɵɵFactoryDeclaration<IMaskFactory, never>;
~~~~~~~~~~~~~~~~~~~~
node_modules/angular-imask/imask-factory.d.ts:6:22 - error TS2694: Namespace '"/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectableDeclaration'. 6 static ɵprov: i0.ɵɵInjectableDeclaration<IMaskFactory>;
~~~~~~~~~~~~~~~~~~~~~~~
node_modules/angular-imask/imask.directive.d.ts:46:21 - error TS2694: Namespace '"/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'. 46 static ɵfac: i0.ɵɵFactoryDeclaration<IMaskDirective<any>, [null, null, null, null, { optional: true; }]>;
~~~~~~~~~~~~~~~~~~~~
node_modules/angular-imask/imask.directive.d.ts:47:21 - error TS2694: Namespace '"/node_modules/@angular/core/core"' has no exported member 'ɵɵDirectiveDeclaration'. 47 static ɵdir: i0.ɵɵDirectiveDeclaration<IMaskDirective<any>, "[imask]", ["imask"], { "imask": "imask"; "unmask": "unmask"; "imaskElement": "imaskElement"; }, { "accept": "accept"; "complete": "complete"; }, never>;
~~~~~~~~~~~~~~~~~~~~~~
node_modules/angular-imask/imask.pipe.d.ts:7:21 - error TS2694: Namespace '"/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'. 7 static ɵfac: i0.ɵɵFactoryDeclaration<IMaskPipe, never>;
~~~~~~~~~~~~~~~~~~~~
node_modules/angular-imask/imask.pipe.d.ts:8:22 - error TS2694: Namespace '"/node_modules/@angular/core/core"' has no exported member 'ɵɵPipeDeclaration'. 8 static ɵpipe: i0.ɵɵPipeDeclaration<IMaskPipe, "imask">;
~~~~~~~~~~~~~~~~~
node_modules/angular-imask/directive.module.d.ts:5:21 - error TS2694: Namespace '"/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'. 5 static ɵfac: i0.ɵɵFactoryDeclaration<IMaskDirectiveModule, never>;
~~~~~~~~~~~~~~~~~~~~
node_modules/angular-imask/directive.module.d.ts:6:21 - error TS2694: Namespace '"/node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDeclaration'. 6 static ɵmod: i0.ɵɵNgModuleDeclaration<IMaskDirectiveModule, [typeof i1.IMaskDirective], [typeof i2.CommonModule], [typeof i1.IMaskDirective]>;
~~~~~~~~~~~~~~~~~~~~~
node_modules/angular-imask/directive.module.d.ts:7:21 - error TS2694: Namespace '"/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'. 7 static ɵinj: i0.ɵɵInjectorDeclaration<IMaskDirectiveModule>;
~~~~~~~~~~~~~~~~~~~~~
node_modules/angular-imask/imask.module.d.ts:6:21 - error TS2694: Namespace '"/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'. 6 static ɵfac: i0.ɵɵFactoryDeclaration<IMaskModule, never>;
~~~~~~~~~~~~~~~~~~~~
node_modules/angular-imask/imask.module.d.ts:7:21 - error TS2694: Namespace '"/node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDeclaration'. 7 static ɵmod: i0.ɵɵNgModuleDeclaration<IMaskModule, [typeof i1.IMaskPipe], [typeof i2.CommonModule, typeof i3.IMaskDirectiveModule], [typeof i1.IMaskPipe, typeof i3.IMaskDirectiveModule]>;
~~~~~~~~~~~~~~~~~~~~~
node_modules/angular-imask/imask.module.d.ts:8:21 - error TS2694: Namespace '"/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'. 8 static ɵinj: i0.ɵɵInjectorDeclaration<IMaskModule>;

**Comment by hiqbal01** [comment]
I found this stackoverflow for users who are running into issues upgrading their angular version: https://stackoverflow.com/questions/58078033/ng-serve-throwing-angular-core-core-has-no-exported-member-eefactorydef

Your error does not look specific to Novo Elements.

**Comment by npramod189** [comment]
Thank you everyone for the response. The issue is resolved now. According to Github project we were using angular-ismask version - ^6.2.2. We changed this to version - ~6.0.5 and its working fine now.
