### ISSUE TITLE
Bug: Dropdown/Selects no longer allow multiple character typing to jump to option.

### ISSUE THREAD

**Issue by bvkimball** [bullhorn/novo-elements#1291]
Using letters to skip to Drop Down menu options is worse now. You used to be able to type the first few letters to get to the option you wanted, now the system only recognizes the first letter. (e.g. for the Note action type, I used to be able to type "ot" to get Other.note. Now you can press O multiple types to cycle through the options beginning with O."

**To Reproduce**
1. Go to [dropdown examples](http://bullhorn.github.io/novo-elements/docs/#/components/dropdown/examples)
2. Then open "lots of data points"
3. Type C then Type O

**Expected behavior**
Drop down should scroll to the first Option that starts with CO

**Actual behavior**
Drop down scrolls to the first Option that starts with O

Change caused in v6

Uncertain if we will fix

**Comment by bvkimball** [comment]
This was reported through client feedback session.  I seem to recall this is how it worked but did not verify this was old functionality.  Do we think it is better or worse?  The new implementation mimics that of default "Select" components....  I think we have to question expected behavior for a11y. 

ie: https://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-scrollable.html

**Comment by hiqbal01** [comment]
As per https://www.w3.org/TR/wai-aria-practices-1.1/#listbox_kbd_interaction

Type-ahead is recommended for all listboxes, especially those with more than seven options:
Type a character: focus moves to the next item with a name that starts with the typed character.
Type multiple characters in rapid succession: focus moves to the next item with a name that starts with the string of characters typed.

So I think we should make this fix.

**Comment by michael-amaya-bh** [comment]
This was completed with https://github.com/bullhorn/novo-elements/pull/1294.
