### ISSUE TITLE
[Tiles] Default state styles

### ISSUE THREAD

**Issue by amrutha-rajiv** [bullhorn/novo-elements#134]
##### **I'm submitting a [BUG REPORT]**
default state styles don't work when element is hidden on the form in the initial state

##### **What is the current behavior?**

![screen shot 2016-08-02 at 2 02 20 pm](https://cloud.githubusercontent.com/assets/1760101/17339678/f0e5a722-58ba-11e6-8981-0cdadf486dc8.png)

##### **steps to reproduce**
hide element on form load (hide non-required fields) and unhide it (field with tile input would be an optional field)

##### **What is the expected behavior?**
![image](https://cloud.githubusercontent.com/assets/1760101/17339719/2ec34ebe-58bb-11e6-9edb-b34072cdac71.png)

**Comment by amrutha-rajiv** [comment]
I will pick this up after the RC4 changes are complete

**Comment by krsween** [comment]
By hidden do you mean `hidden` the element attribute or removed from the DOM?

**Comment by jgodi** [comment]
Most likely do to the fact that all the logic is defined in `ngOnInit`. Thanks for waiting for RC.4 :)

**Comment by amrutha-rajiv** [comment]
`hidden` attribute on `form-field` tile's `active-indicator` is there in the DOM but it doesn't have any `width` from the active element to go by
