### ISSUE TITLE
Documentation page not updated

### ISSUE THREAD

**Issue by rnitu** [bullhorn/novo-elements#1404]
Documentation page is a couple versions behind newest Novo release.
http://bullhorn.github.io/novo-elements/docs

![Screenshot 2023-03-16 102559](https://user-images.githubusercontent.com/18534441/225648122-ff19d8d0-ca0d-4425-93f9-43f7b1b8f474.png)

**Comment by dvoegelin** [comment]
Got this updated recently. No new updates pages in a while but I will be updating the hosted docs with every new release going forward.
