### ISSUE TITLE
[Question]: Moving data between Opprotunites and Job Orders

### ISSUE THREAD

**Issue by NealShuris** [bullhorn/novo-elements#1417]
I have been unable to get data to transfer from the opportunity record to the job order on conversion, is there a pageContext like the "MoveToPlacement" one for when an opportunity is converted to a jobOrder? Or is there a different way to carry that data forward?

**Comment by michael-amaya-bh** [comment]
This issue is not related to this repo, but rather to the bullhorn ATS application. I would contact support for the ATS product to get this issue properly resolved.
