### ISSUE TITLE
[Activity Table Filters] - Auto-Focus on Field

### ISSUE THREAD

**Issue by marycurtis** [bullhorn/novo-elements#143]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)
##### **What is the current behavior?**

No auto-focus on field in some of the filter dropdowns in the activity tables.
##### **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://plnkr.co or similar. (TODO - make a starter plnkr)
- Navigate to Company 129333
- Click Activity
- Click Opportunities
- Click the filter icon on the "Opp Owner" column
- Click on the filter icon
- The field is not in focus 

![screen shot 2016-08-08 at 2 28 06 pm](https://cloud.githubusercontent.com/assets/16156795/17491198/9e6a36de-5d74-11e6-9677-fde7df15611a.png)
##### **What is the expected behavior?**

When clicking the filter icon, the field should be in focus.

![screen shot 2016-08-08 at 2 30 31 pm](https://cloud.githubusercontent.com/assets/16156795/17491222/b024a9b8-5d74-11e6-95f6-aa596d2f79cb.png)
##### **What is the motivation / use case for changing the behavior?**

It is more efficient for the user to only click once to filter the column. The behavior is also inconsistent across the columns and tables - some auto-focus and some do not.

**Comment by marycurtis** [comment]
@jgodi @asibilia Any word on this issue? Still seeing it on a handful of columns on tearsheets

**Comment by jgodi** [comment]
Ya, isn't fixed yet.
