### ISSUE TITLE
Leaving Stepper route creates white screen in the next route clicked

### ISSUE THREAD

**Issue by ericflores108** [bullhorn/novo-elements#1440]
**Describe the bug**
Novo Elements is showing a blank screen after leaving the stepper route. 

**To Reproduce**
1. Open http://bullhorn.github.io/novo-elements/#/layouts/stepper
2. Click on Stepper
3. Then click on Sidenav
4. Check in developer tool console, 
`Error: Uncaught (in promise): TypeError: this.outlet.show is not a function
TypeError: this.outlet.show is not a function`
` Error: Uncaught (in promise): ObjectUnsubscribedError: object unsubscribed`

**Expected behavior**
Show Sidenav and not a white screen after leaving the Stepper. 

**Actual behavior**
Error occurs. Showing white screen after leaving the Stepper.

**Comment by michael-amaya-bh** [comment]
Closing, as this is now resolved.
