### ISSUE TITLE
[Question] Call external API on create/update

### ISSUE THREAD

**Issue by JulianeSMF** [bullhorn/novo-elements#1458]
Hi,

we want to implement a possibility to send a notification email to a candidate if a new job is published which suits to his profile. 
For that to work, we need to inform our application’s backend (external API) when a new JobOrder entity was created or updated.
We found so far 2 ways which might be possible, one of which is very hacky and from the documentation alone, we're not sure if any of them would actually work:

Possibility 1:
- creating a page interaction (https://bullhorn.github.io/Page-Interaction-documentation) on job offerings which sends an api request (http) with the job’s ID to our API on save via the appbridge

Possibility 2:
- writing a field interaction (http://bullhorn.github.io/novo-elements/docs/#/utils/field-interactions) for one of the fields which grabs the save button via id, and adds an API call to its onclick, on init of the field.

In both cases, our current goal is just to inform our backend of the change with the API. Getting the JobOrder’s data and everything after would be handled by our backend.

Our questions are:
- Did we miss another easier way to accomplish our goal of informing external software of updates in an entity type?
- Can we call external URLs / http requests from the Appbridge?
- Are there any other problems that hinders either of the two proposed solutions from working?

Thanks in Advance for any hint or idea
Juliane

**Comment by michael-amaya-bh** [comment]
Hello Julia, 

Thanks for reaching out. A better solution would be to use our backend REST API to subscribe to change events for your particular entity. You can find more information in our REST API docs referenced below.

Here is what is involved in the high level process
1. Ensure you have a valid API key to make bullhorn REST API calls (can get this from support if you don't have one)
2. Login with your API key
3. Use a PUT call to create a subscription event - http://bullhorn.github.io/rest-api-docs/#put-event-subscription
4. Use a GET call to get events for your subscription - http://bullhorn.github.io/rest-api-docs/#get-event-subscription

I hope this helps, let me know if you have any further questions or concerns.
