### ISSUE TITLE
[Table] - Column width is inconsistent based on the data displayed in comments column

### ISSUE THREAD

**Issue by rjayavelu** [bullhorn/novo-elements#146]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)
##### **What is the current behavior?**

The comments column with more text has a wider comments columns. The entire table column alignment changes.
##### **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Login to Novo
Fast find a record with more than 10 notes added.
Add note with more than 2 or 3 sentences in the comments section.
Go to overview -> Activity -> Notes
Navigate between pages
The comments column with more text has a wider comments columns. The entire table column alignment changes.
##### **What is the expected behavior?**

The table column alignment should not change based on the data in each column.
##### **Please tell us about your environment:**
- Angular version: 2.0.0-RC.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
##### **Other information**

_(e.g. detailed explanation, screenshots, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)_

**Comment by jgodi** [comment]
Closing, this will be on a case by case basis where it is implemented
