### ISSUE TITLE
Bug: Dynamic Form - cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by ericflores108** [bullhorn/novo-elements#1482]
Similar to issue #1198 , when clicking "Show All Fields" button on the Dynamic Form example, it says ERROR TypeError: Cannot read properties of undefined (reading 'includes')

![image](https://github.com/bullhorn/novo-elements/assets/95382086/1745a718-cd25-4c83-8f82-36e0398c9be2)

**Comment by michael-amaya-bh** [comment]
This is now fixed.
