### ISSUE TITLE
[TipWell] Modify icon color to #aaaaaa

### ISSUE THREAD

**Issue by eblackmore3223** [bullhorn/novo-elements#151]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)

##### **What is the current behavior?**
TipWell icon color is currently too dark.

##### **What is the expected behavior?**
TipWell icon color should be #aaaaaa

##### **What is the motivation / use case for changing the behavior?**
The icon is a bit too high contrast right now. It draws the eye too heavily.

**Comment by jgodi** [comment]
Will tackle this after the RC.5 branch
