### ISSUE TITLE
[Date Picker] - Errors on select year from dropdowns in range picker

### ISSUE THREAD

**Issue by MagicAardvark** [bullhorn/novo-elements#155]
##### **What is the current behavior?**
Open Date Range picker, click on year to open year selector. Picker errors and year is not selected

##### **What is the expected behavior?**
Year should select and load new year data

##### **Please tell us about your environment:**

- Angular version: 2.0.0-RC.4
- Browser:all

**Comment by krsween** [comment]
Also, Months have the same behavior. If you aren't using the arrow buttons, they trigger an error.
