### ISSUE TITLE
[Pickers] - Search icon is overlapping chips

### ISSUE THREAD

**Issue by marycurtis** [bullhorn/novo-elements#175]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)

##### **What is the current behavior?**

When selecting multiple values from a picker, the chips remain in 1 line until no space remains, and then they continue onto the next line.

##### **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://plnkr.co or similar. (TODO - make a starter plnkr)

* Fast add task
* Click on the "assigned to" field
* Select multiple records
* Notice that the search icon overlaps the record on the right

<img width="483" alt="screen shot 2016-08-30 at 3 36 36 pm" src="https://cloud.githubusercontent.com/assets/16156795/18104301/878f65be-6ec8-11e6-855e-520ce1dd7f9c.png">

##### **What is the expected behavior?**

The max-width should be decreased, so that if a chip doesn't fit on the first line, it gets pushed to the next line without colliding with the search icon.

##### **What is the motivation / use case for changing the behavior?**

The user will have difficulty removing the chip on the right if the search icon is on top of it.

**Comment by jgodi** [comment]
Fixed in https://github.com/bullhorn/novo-elements/commit/f293b60b9d6b02994e20acb30f465f67a153f7e8
