### ISSUE TITLE
[Chips] - Able to select same record multiple times

### ISSUE THREAD

**Issue by rjayavelu** [bullhorn/novo-elements#176]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)
##### **What is the current behavior?**

Can pick same record multiple times from the picker field
##### **What is the expected behavior?**

Should not be able to pick same record multiple times for a picker field.
##### **Please tell us about your environment:**
- Angular version: 2.0.0-RC.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
##### **Other information**

_(e.g. detailed explanation, screenshots, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)_

**Comment by MagicAardvark** [comment]
this should be made configurable 
```unique=true/false```

**Comment by jgodi** [comment]
This is for Chips right? Picker is single value, so the value gets replaced over the old one.

**Comment by MagicAardvark** [comment]
Yes it will be chips.
