### ISSUE TITLE
[Table] No data returned when filtered with same start date and end date .

### ISSUE THREAD

**Issue by rjayavelu** [bullhorn/novo-elements#178]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)
##### **What is the current behavior?**

Custom Date Range filtering in the activity table with same start date and end date does not return data 
##### **What is the expected behavior?**

Should display data if the date field data matches the selected date.
##### **Please tell us about your environment:**
- Angular version: 2.0.0-RC.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
##### **Other information**

_(e.g. detailed explanation, screenshots, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)_

**Comment by jgodi** [comment]
One thing to investigate on this is the start/end, the start should be at the begin of the day and the end should be the end of the day.

**Comment by rjayavelu** [comment]
This issue is not reproducible now. Could have been fixed along with the earlier fixes to date filter. Hence closing the ticket.
