### ISSUE TITLE
[Forms] - Labels are appearing on top of field text

### ISSUE THREAD

**Issue by marycurtis** [bullhorn/novo-elements#198]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)
##### **What is the current behavior?**
- When the form is initially opened, the date label appears on top of the helper text. The labels appear as they would when the fields are filled, and then they move down into the fields.

![screen shot 2016-09-22 at 10 18 21 am](https://cloud.githubusercontent.com/assets/16156795/18751693/e81b7c46-80ad-11e6-82b9-827b37f58a2f.png)
- After filling out a field, the label moves back down to cover the field text

![screen shot 2016-09-22 at 10 20 30 am](https://cloud.githubusercontent.com/assets/16156795/18751777/413e8afc-80ae-11e6-99ff-77a6eed5c56a.png)
- If the user clicks on a field, the label moves up. If the user doesn't fill out that field, but clicks on another field instead, the field label still shows above (as if the field was filled)

![screen shot 2016-09-22 at 10 22 10 am](https://cloud.githubusercontent.com/assets/16156795/18751829/727f5736-80ae-11e6-9186-d5eeee9f5c0c.png)
- Dropdown collapse icon is appearing on the left side of the field

![screen shot 2016-09-22 at 10 28 38 am](https://cloud.githubusercontent.com/assets/16156795/18752153/82f8da3c-80af-11e6-9c12-8ab1da4bf810.png)
##### **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://plnkr.co or similar. (TODO - make a starter plnkr)
- Fast add a job
- Notice the labels moving when the page loads
- Notice the date label appearing over the helper text
- Click and type into fields to see the labels appearing over the field text
- Click into 2 fields multiple times. Notice the labels moving in unison.
- Navigate to a dropdown field. Notice the icon is on the wrong side of the field.
##### **What is the expected behavior?**
- When the form loads, the labels should appear in their appropriate locations
- When a field is filled, the label should appear above
- When a field is clicked, the label should move above
- When a field is clicked, but not filled, and then another field is clicked, the label should appear in the field rather than above the field
- Clicking into a field should only move the label for that field, not for any others
- Labels should appear above any fields with helper text
- Dropdown collapse icon should appear on the right side of the field

**Comment by jgodi** [comment]
@asibilia This is fixed now?

**Comment by asibilia** [comment]
@jgodi some of them. Investigating others

**Comment by jgodi** [comment]
Fixed: https://github.com/bullhorn/novo-elements/commit/933abe950afbae945fabb9cc9a95a7dd8a48fa90
