### ISSUE TITLE
[Chips] - Entity colors

### ISSUE THREAD

**Issue by marycurtis** [bullhorn/novo-elements#219]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)
##### **What is the current behavior?**

Chips with colored circles are only available for internal users. Chips for entities do not have colored circles.
##### **What is the expected behavior?**

Entity chips should include a circle that is the color of the entity selected.
##### **What is the motivation / use case for changing the behavior?**

To indicate what entity the value is.

**Comment by marycurtis** [comment]
@jgodi @asibilia Not sure which one of you will be working on this, but Kyle wants you to sync with him when you do because he is working on getting multiple entity types into 1 picker

**Comment by jgodi** [comment]
Multiple entity types works out of the box in the pickers/chips. It is all based on what is returned from the server call. No one is working on this currently.

**Comment by marycurtis** [comment]
Spicetroopers will be completing this work in https://jira.bullhorn.com/browse/BH-43232
