### ISSUE TITLE
[Dropdowns] - Selected item remains in hover state when returning to dropdown

### ISSUE THREAD

**Issue by marycurtis** [bullhorn/novo-elements#220]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)
##### **What is the current behavior?**

When selecting an option from the ACTIONS dropdown on a record, it should not still remain in a hover state when returning to the dropdown. 
##### **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://plnkr.co or similar. (TODO - make a starter plnkr)
- Navigate to a record
- Select ACTIONS
- Select either "Email" or "Send SMS Message"
- Close the bowling alley tab
- Navigate back to the record and click on ACTIONS again
- Notice that the option you previously selected is still in a hover state
- Click outside of the ACTIONS dropdown
- Click on ACTIONS again
- Notice the option is still in a hover state
- Hover over the other dropdown options, and notice that it clears
##### **What is the expected behavior?**

The previously selected option in the dropdown list should not have a hover state (without hovering) when returning to the dropdown. 
##### **What is the motivation / use case for changing the behavior?**

The dropdown should look the same every time it is opened.

**Comment by jgodi** [comment]
No longer an issue, checked 1/14. Closing.
