### ISSUE TITLE
[Table] No data returned when filtering text with special character

### ISSUE THREAD

**Issue by rjayavelu** [bullhorn/novo-elements#240]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)

##### **What is the current behavior?**

No data returned when filtering text with special character

##### **What is the expected behavior?**

Should be able to filter text with special characters

##### **Please tell us about your environment:**

- Angular version: 2.0.0-RC.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

##### **Other information** 
_(e.g. detailed explanation, screenshots, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)_

**Comment by jgodi** [comment]
Since the table filtering is either offloaded to REST or there are column filter functions that one can use, this issue isn't in NovoElements, it is in the implementation. Closing.
