### ISSUE TITLE
[Pickers] - Dropdown doesn't automatically open when same search is entered twice

### ISSUE THREAD

**Issue by marycurtis** [bullhorn/novo-elements#254]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)

##### **What is the current behavior?**
The dropdown opens the first time the user searches, but doesn't open the second time if the user searches for the same value.

##### **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://plnkr.co or similar. (TODO - make a starter plnkr)
* Type in a value to search in a picker
* Select the value from the dropdown
* Search for the same value that you originally searched for
* Notice the picker doesn't open automatically unless you search for a different value

See attached video.
[Pickers.zip](https://github.com/bullhorn/novo-elements/files/596107/Pickers.zip)

##### **What is the expected behavior?**
The dropdown should automatically expand when you start typing, even if the second search is the same as the first.

**Comment by jgodi** [comment]
No longer an issue, checked 1/14. Closing.
