### ISSUE TITLE
[Pickers] - Label overlaps text in field when chip is backspaced

### ISSUE THREAD

**Issue by marycurtis** [bullhorn/novo-elements#255]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)

##### **What is the current behavior?**
The field label overlaps text in the field when a chip is selected and then backspaced.

##### **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://plnkr.co or similar. (TODO - make a starter plnkr)
See video:

[OverlappingLabel.zip](https://github.com/bullhorn/novo-elements/files/596114/OverlappingLabel.zip)

##### **What is the expected behavior?**
Label should move above when the user types in the field.

**Comment by jgodi** [comment]
Tested 1/14, no longer an issue. Closing.
