### ISSUE TITLE
[Toast] - Allow toast service open/alert to take an offset for positioning

### ISSUE THREAD

**Issue by monroepe** [bullhorn/novo-elements#267]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)

##### **What is the current behavior?**

The toast service alert doesn't take an offset for positioning 

##### **What is the expected behavior?**

The toast service open/alert should take an offset for positioning

##### **What is the motivation / use case for changing the behavior?**

It allows someone to position a toast from the toast service if they need to.

**Comment by jgodi** [comment]
Not really needed, closing
