### ISSUE TITLE
[Multi-select Pickers] - Modify disabled state

### ISSUE THREAD

**Issue by marycurtis** [bullhorn/novo-elements#318]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)

##### **What is the current behavior?**
The disabled state of multi-select pickers includes a "clear all" button and the chips include an "x" icon.

<img width="598" alt="screen shot 2016-12-30 at 10 28 00 am" src="https://cloud.githubusercontent.com/assets/16156795/21567538/d1234666-ce7a-11e6-9200-10fb84c26766.png">

##### **What is the expected behavior?**
Multi-select pickers should not have a clear all button or "x" icons in chips when in a disabled state.

##### **What is the motivation / use case for changing the behavior?**
Consistency with the disabled state of single-select pickers, where there is no clear button in the field.

**Comment by jgodi** [comment]
Fixed with https://github.com/bullhorn/novo-elements/commit/07aafd357661e7c049a89d186157c72702e89807
