### ISSUE TITLE
[Toast] - Ability to add timer for inline toasts

### ISSUE THREAD

**Issue by asibilia** [bullhorn/novo-elements#32]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](http://google.com)
##### **I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] question about the decisions made in the repository
##### **What is the current behavior?**

Inline `novo-toast` elements are tied to `*ngIf` to show or hide. `Time` properties on inline `novo-toast` elements are set to `null`.
##### **What is the expected behavior?**

Use a `timer` attribute on inline `novo-toast` elements to control show or hide. `timer` attribute should allow for a time in `ms` or for `indefinite`.
##### **What is the motivation / use case for changing the behavior?**
- Added/improved functionality

**Comment by jgodi** [comment]
Closing this, the inline toasts would be tied to `*ngIf` on the `<novo-toast>` element, so inside the component we would only be able to `removeFromParent` on a timer which would make it hard for the user to display it again if needed. 

If the user needs timers for inline-toasts, then they will have to `setTimeout` on their end and toggle the boolean tied to `*ngIf`
