### ISSUE TITLE
[Modal] - Align modal to the top of the page/frame

### ISSUE THREAD

**Issue by stewmorg** [bullhorn/novo-elements#347]
##### **What is the current behavior?**

Modal is center aligned to the frame it renders it. It would be good if it could be positioned relative to the top of the page

##### **What is the motivation / use case for changing the behavior?**

Reduce wasted space on the when rendering a modal in a custom Tab

##### **Please tell us about your environment:**

- Angular version: 2.0.0

##### **Other information** 
![image](https://cloud.githubusercontent.com/assets/956895/21905079/1e69ea0a-d8fe-11e6-977f-a15ec9b2052a.png)

**Comment by jgodi** [comment]
Hey Stewart, the styling for that comes from `novo-modal-container` styling. I will look into ways to improve the opening of modals to be able to do something like `modalService.open(MyModal, {SCOPE}, ModalPosition.TOP)` to open at the top rather then the center.

In the meantime, you can force all the modals on that custom tab to open to the top by making a small CSS modification. In your app just put:

```
novo-modal-container {
  align-items: top !important;
}
```

then you can just add some padding/margins to make it look better.

Also, just a side note you can also add `background: rgba(0, 0, 0, 0);` to that to get rid of the dark background when the modal is open, but the content underneath will still remain un-clickable.

**Comment by michael-amaya-bh** [comment]
Closing due to age, this should not be an issue. Please, re-open if you are still experiencing this issue.
