### ISSUE TITLE
[Forms] - Fields when disabled, overrides with the label and value

### ISSUE THREAD

**Issue by rjayavelu** [bullhorn/novo-elements#353]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)

##### **What is the current behavior?**
The label and field value overlaps on top of eachother

##### **What is the expected behavior?**

The label and the value for the disabled field should be clearly visible and should not override each other.

##### **Please tell us about your environment:**

- Angular version: 2.0.0-RC.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

##### **Other information** 
_(e.g. detailed explanation, screenshots, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)_

**Comment by jgodi** [comment]
Fixed with https://github.com/bullhorn/novo-elements/commit/ae846c55039adbeb151537514ecec089b7b3d927
