### ISSUE TITLE
if a field is required=true through form interactions, it does not ‘verify’ the field contents

### ISSUE THREAD

**Issue by plloydbullhorn** [bullhorn/novo-elements#354]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)

##### **What is the current behavior?**
When a field is 'required=true' through form interactions, verification that the newly required field is populated does not currently happen.

IE) Within Placements: If otherHourlyFee has a value, otherHourlyFeeComments is required. When we populate otherHourlyFee then otherHourlyFeeComments becomes required, but has a checkmark next to the field as if it was populated even though it's not.
![image](https://cloud.githubusercontent.com/assets/16294940/22041176/623a0b5e-dccb-11e6-88f5-2e02f0ad3688.png)

##### **Please tell us about your environment:**

- Angular version: 2.0.0-RC.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

##### **Other information** 
_(e.g. detailed explanation, screenshots, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)_

**Comment by jgodi** [comment]
@krsween This isn't a NovoElements bug right? Its in the interaction for the field?

**Comment by MagicAardvark** [comment]
It is, it can be recreated in novo elements field interactions demo.

If you set a field to required through setRequired() it is automatically valid despite being empty.
