### ISSUE TITLE
[Table] Filter icons are displayed in unintended table columns

### ISSUE THREAD

**Issue by rjayavelu** [bullhorn/novo-elements#393]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)

##### **What is the current behavior?**
Go to Commissions tab for a placement record.
The internal/external commission table columns displays filter icons

##### **What is the expected behavior?**

Filter icons should not be displayed

##### **Please tell us about your environment:**

- Angular version: 2.0.0-RC.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

##### **Other information**
_(e.g. detailed explanation, screenshots, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)_

**Comment by jgodi** [comment]
Closing as this is not the repo for the change.
