### ISSUE TITLE
[Forms] - Validation error messages do not support localization

### ISSUE THREAD

**Issue by bvkimball** [bullhorn/novo-elements#395]
Validation error messages are just static text and do not support localization. You should be able to override the default validate error messages.

see:
https://github.com/bullhorn/novo-elements/blob/master/src/elements/form/Control.ts#L110-L118

- Angular version: all
- Browser: all

**Comment by jgodi** [comment]
Fixed in https://github.com/bullhorn/novo-elements/commit/b41848d5ece06103d4575b95082e62d4380010c6
