### ISSUE TITLE
[Forms] - Section header text/icon alignment

### ISSUE THREAD

**Issue by marycurtis** [bullhorn/novo-elements#406]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)

##### **What is the current behavior?**
The icon on section headers is slightly lower than the text. See screenshot:

<img width="1242" alt="screen shot 2017-02-16 at 2 49 08 pm" src="https://cloud.githubusercontent.com/assets/16156795/23038257/5c23453e-f457-11e6-86c5-3fe114bd7287.png">

##### **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
* Login to Novo
* Add a record (any entity with section headers configured)

##### **What is the expected behavior?**
Icon should be moved up so that it vertically aligns with the section header text.

**Comment by jgodi** [comment]
Fixed in https://github.com/bullhorn/novo-elements/commit/b41848d5ece06103d4575b95082e62d4380010c6
