### ISSUE TITLE
[Tipwell] - Text slightly off center when not multiline

### ISSUE THREAD

**Issue by monroepe** [bullhorn/novo-elements#407]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)

##### **What is the current behavior?**
Currently if the text is single line with an icon, the text is not centered vertically relative to the icon.
![novo-elements-demo](https://cloud.githubusercontent.com/assets/7033445/23040020/670f00c0-f455-11e6-9ab5-6e2f11a23d10.PNG)

##### **What is the expected behavior?**
The text should be centered vertically when single line of text.

##### **Please tell us about your environment:**

- Angular version: 2.0.0-RC.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

##### **Other information**
_(e.g. detailed explanation, screenshots, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)_

**Comment by jgodi** [comment]
Fixed in https://github.com/bullhorn/novo-elements/commit/b41848d5ece06103d4575b95082e62d4380010c6
