### ISSUE TITLE
[Forms] - Toggle appearing on missing required fields page

### ISSUE THREAD

**Issue by marycurtis** [bullhorn/novo-elements#409]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)

##### **What is the current behavior?**
When saving a form with not all required fields filled, any toggles on the form also appear on the "missing required fields" form.

##### **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
* Login to revathi-backend/
* Add a Contact
** Don't fill out any fields
* Click save
* Notice there is a toggle appearing on the "missing required fields" page

![screen shot 2017-02-16 at 5 34 43 pm](https://cloud.githubusercontent.com/assets/16156795/23044441/40710922-f46e-11e6-823a-c07c9682c56a.png)

##### **What is the expected behavior?**
The toggle should not appear on the "missing required fields" page when it has a selection.

**Comment by jgodi** [comment]
Fixed in https://github.com/bullhorn/novo-elements/commit/b41848d5ece06103d4575b95082e62d4380010c6
