### ISSUE TITLE
Header element, unable to make mobile sticky header

### ISSUE THREAD

**Issue by MagicAardvark** [bullhorn/novo-elements#41]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](http://google.com)

##### **I'm submitting a ...**
* [ ] bug report
* [X] feature request
* [ ] question about the decisions made in the repository

##### **What is the current behavior?**
section.primary is transparent

##### **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar. (TODO - make a starter plnkr)

##### **What is the expected behavior?**
The top bar should not be transparent when position:fixed

##### **What is the motivation / use case for changing the behavior?**
I would like to make a sticky header in mobile which is made up of 3 sections

[BTN] [HEADER] [BTN] <- should be sticky to top (position:fixed)
[SECTION] <- should slide under header when user scrolls
[TAB SECTION] <- should become sticky under HEADER (becomes fixed at certain point)

The top bar uses the section.primary class and currently has no background color so it is transparent when the section content slides under it.

What I would like is the background color to also be applied to section.primary to allow me to have this functionality. 

##### **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Ionic 2
- Browser: all 

##### **Other information** 
![screen shot 2016-05-05 at 10 32 32 am](https://cloud.githubusercontent.com/assets/13399000/15046246/c8cf22ee-12ac-11e6-9a0f-3845f9334677.png)
![screen shot 2016-05-05 at 10 32 46 am](https://cloud.githubusercontent.com/assets/13399000/15046247/c998eba6-12ac-11e6-9e86-4c6102eaf23f.png)

**Comment by jgodi** [comment]
Sounds like an Alec issue :)
