### ISSUE TITLE
Is there a starter layout or template?

### ISSUE THREAD

**Issue by biapar** [bullhorn/novo-elements#419]
Is there a starter layout or template?

**Comment by MagicAardvark** [comment]
Hi Biapar, we currently do not have a starter template. But we do have examples on our demo page at http://bullhorn.github.io/novo-elements/#/

**Comment by jgodi** [comment]
Yes, the documentation and starter repo's will begin to emerge in the coming weeks/months. Refer to https://github.com/bullhorn/novo-elements/issues/273 please.

**Comment by biapar** [comment]
Hi @MagicAardvark I mean a layout with sidebar ( drawer ), header, etc...
Thanks.
