### ISSUE TITLE
Angular 4 compatible?

### ISSUE THREAD

**Issue by biapar** [bullhorn/novo-elements#456]
Is Novo compatible with Angular Cli and Angular 4?

**Comment by jgodi** [comment]
Great question, thank you for asking. Yes, this library is compatible with both the CLI and Angular 4. Better documentation and actually upgrading the library to Angular 4 for this is coming down the pipeline, but here is how you would get started.

In your `.angular-cli.json` you will have to add to your `apps[0]`:

```
 "stylePreprocessorOptions": {
      "includePaths": [
        "../node_modules/hint.css/src",
        "../node_modules/novo-elements"
      ]
    },
```

Then in your `app.module.ts` you will add:

```
import { NovoElementsModule, NovoElementProviders } from 'novo-elements';

@NgModule({
    imports: [
        NovoElementsModule,
        NovoElementProviders.forRoot(),
    ]
})
```

Let me know if you have any questions!
