### ISSUE TITLE
[Calendar] - Always setting date in picker to today

### ISSUE THREAD

**Issue by jeremy-dobler** [bullhorn/novo-elements#460]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)

##### **What is the current behavior?**
No matter what you set the initial value to for a Calendar picker, the UI is displaying today's date.

##### **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Look at CalendarDemo of novo-elements
start=one month before today
end=one month after today
But the picker is displaying today's date

**use of start/end variables in calendar picker**
https://github.com/bullhorn/novo-elements/blob/master/demo/pages/elements/calendar/templates/CalendarDemo.html#L9

**start/end variable declarations**
https://github.com/bullhorn/novo-elements/blob/master/demo/pages/elements/calendar/CalendarDemo.ts#L52

##### **What is the expected behavior?**
UI should display the date that you pass in for the start/end values

##### **Please tell us about your environment:**

- Looking at github demo site at novo-elements#2.0.170
- Browser: Chrome - Version 57.0.2987.133 (64-bit)

##### **Other information**
_(e.g. detailed explanation, screenshots, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)_

**Comment by jgodi** [comment]
Fixed with https://github.com/bullhorn/novo-elements/commit/4b521f4c54fc5d8d60f1820d2e5229a976d63c5f
