### ISSUE TITLE
[Pickers] Icon is not aligned

### ISSUE THREAD

**Issue by marycurtis** [bullhorn/novo-elements#461]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)

##### **What is the current behavior?**
The "x" and magnifying glass icons on single-select pickers are not vertically aligned.

##### **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
<img width="582" alt="screen shot 2017-04-19 at 1 53 22 pm" src="https://cloud.githubusercontent.com/assets/16156795/25194258/e5dc5b0e-2507-11e7-9f57-84f410c627c7.png">

<img width="603" alt="screen shot 2017-04-19 at 1 53 50 pm" src="https://cloud.githubusercontent.com/assets/16156795/25194261/e8179b22-2507-11e7-9099-f09b9e8e7b56.png">

##### **What is the expected behavior?**
Icons should be aligned the same way as multi-select pickers:

<img width="580" alt="screen shot 2017-04-19 at 1 53 56 pm" src="https://cloud.githubusercontent.com/assets/16156795/25194284/fa0f7c28-2507-11e7-904e-16eeadc0a674.png">

**Comment by jgodi** [comment]
Fixed: https://github.com/bullhorn/novo-elements/commit/d88813f9439176371d48c552398a16b82df8258d
