### ISSUE TITLE
Tabs: Add "disabled" input to novo-tab

### ISSUE THREAD

**Issue by amrutha-rajiv** [bullhorn/novo-elements#466]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)

##### **I'm submitting a FEATURE REQUEST**
[disabled]="true" should disable the action of being able to click on the tab to navigate to it

##### **Please tell us about your environment:**

- Angular version: 2.0.0-RC.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

##### **Other information**
_(e.g. detailed explanation, screenshots, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)_

**Comment by yi-ren** [comment]
![notallowed](https://cloud.githubusercontent.com/assets/13206866/25677124/c9356020-3012-11e7-9c66-cabea9d8e97c.png)

**Comment by amrutha-rajiv** [comment]
Implemented in #470
