### ISSUE TITLE
Date Time Picker cutting off days added to previous month

### ISSUE THREAD

**Issue by kjsperling** [bullhorn/novo-elements#467]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)

##### **What is the current behavior?**

When a month displays the grayed out days from the next month, when you navigate to the next month, the days are not present.

##### **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Locate a Date Time Picker (or view the issue here http://bullhorn.github.io/novo-elements/#/calendar) if you select May 2017, you see the grayed out days for June 2017 and when you navigate to June, the days start at the 4th.

##### **What is the expected behavior?**
The grayed out dates from the next month should still fill in the last row of the calendar for the current month, but when you navigate to the next month, it should show all the days.

##### **Please tell us about your environment:**
- Browser: Chrome 58.0.3029.81

##### **Other information**
- See attached screenshot
![datepicker](https://cloud.githubusercontent.com/assets/13823440/25676820/7ce9b3d4-3011-11e7-8791-0a9169f687e7.PNG)

**Comment by jgodi** [comment]
Fixed: 934d245d7a9c9a2494e6aee45af2f461423ca522
