### ISSUE TITLE
[Question] Icons not showing up

### ISSUE THREAD

**Issue by BRS999** [bullhorn/novo-elements#488]
Hello,

I've successfully imported novo-elements!

I noticed the icons are not displaying correctly.

I've included the paths in my .angular-cli.json file.

```
      "stylePreprocessorOptions": {
        "includePaths": [
          "../node_modules/hint.css/src",
          "../node_modules/novo-elements"          
        ]
```

And I've included these imports in my styles.scss file.

```
@import "hint";
@import "novo-elements";
```

Any suggestions?

I'm using Angular 4.

![icons](https://user-images.githubusercontent.com/6516437/27347807-ec711de0-55bf-11e7-9ac4-615f6081610c.jpg)

**Comment by jgodi** [comment]
You will need to add ```    <link href='//fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900' rel='stylesheet' type='text/css'>
    <link href="//rawgit.com/bullhorn/bullhorn-icons/development/fonts/Bullhorn-Glyphicons.css" rel="stylesheet" type="text/css">``` to your index.html

**Comment by BRS999** [comment]
I appreciate your help. That works. I see that you have a bullhorn-icons repo. Could I import the iconography that way?

**Comment by BRS999** [comment]
I got it working with

```
      "styles": [
        "styles.scss",
        "../node_modules/bullhorn-icons/fonts/Bullhorn-Glyphicons.css"
      ],
```
Thanks again.
