### ISSUE TITLE
[Question] Using Modals

### ISSUE THREAD

**Issue by BRS999** [bullhorn/novo-elements#518]
Hello,

I'm having an issue using modals. Locally I can invoke and dismiss the modal as expected. However, in a staging environment the modal will "dismiss" but remain in the window with the box shadow.

Here's my modal component

```
export class SimpleModalComponent {

  constructor(private modalRef: NovoModalRef) {
  }

  close() {
    this.modalRef.close();
  }
}
```

And the app component
```
export class AppComponent {

  constructor(private viewContainerRef: ViewContainerRef, private modalService: NovoModalService) {
    this.modalService.parentViewContainer = this.viewContainerRef;

  }

  openModal() {
    this.modalService.open(SimpleModalComponent);
  }
}
```
I've also added the ModalComponent as an entryComponent.

This example notification for the component html.

```
<novo-notification type="success">
    <h1>Woooo!</h1>
    <h2>You did something awesome!</h2>
    <button theme="primary" icon="check" (click)="close()">I'm awesome</button>
</novo-notification>
```
If anything looks awry or if you have any suggestions I would greatly appreciate it!

**Comment by jgodi** [comment]
Hey Ben,

Thank you for the issue!

This all looks solid and this is exactly what we do in our code base too. 

Do you have a sample app that you can send me to? or are there any console errors?

**Comment by BRS999** [comment]
Hello Joshua,

There were seemingly unrelated console errors. I cleared them out and now it's working. 

Thanks for your help!
