### ISSUE TITLE
[Form]: In NovoFormControl, setReadOnly incorrectly calls enabled/disabled

### ISSUE THREAD

**Issue by escarre** [bullhorn/novo-elements#526]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)

##### **What is the current behavior?**
When setting readOnly to true, the formControl calls enabled(). When setting readOnly to false, the formControl calls disabled(). This behavior is reversed.

##### **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
The bug is visible inside the fieldInteractionForm demo. Check 'I have a comment'. The comments field displays, but is in a disabled state, even though setReadOnly(false) as been called on it.

##### **What is the expected behavior?**
setReadOnly(false) should enable the control and vice versa.

##### **Please tell us about your environment:**

- Angular version: 2.0.0-RC.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

##### **Other information**
_(e.g. detailed explanation, screenshots, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)_

**Comment by jgodi** [comment]
Ill fix this in my FieldInteraction Branch

**Comment by escarre** [comment]
I have a fix with a spec i'm about to push up

**Comment by jgodi** [comment]
👍
