### ISSUE TITLE
[Feature Request] - Slideout Service/Component in NovoElements

### ISSUE THREAD

**Issue by BRS999** [bullhorn/novo-elements#528]
Hello,

I'm going through your documentation and I see under composition a mention about flyouts/slideouts. 

In BH you have an excellent slideout for viewing entity details. Is that something that is provided in novo? Or somewhere else perhaps?

Thank you,

Ben

**Comment by jgodi** [comment]
Hello again!

Currently there is not an element from NovoElements that we use for our slideouts. That is something we are looking to bring into this library, but not at the time right now. 

I will convert this issue to a feature request. Feel free to subscribe to this issue to keep up to date.

**Comment by jgodi** [comment]
Just updating this. We will add a service/component for this in our upcoming NovoElements v3 release. In this release you will see WAY better documentation and demos and even sample applications.

It is a work in progress right now and I will keep you updated!

**Comment by michael-amaya-bh** [comment]
Hello, the [aside element](https://bullhorn.github.io/novo-elements/docs/#/components/aside/examples) can be used for slideout support.
