### ISSUE TITLE
[Question] About Table Column Filtering

### ISSUE THREAD

**Issue by BRS999** [bullhorn/novo-elements#530]
Hello,

When it comes to filtering, are there any other options other than entering text or picking a date range?

For instance, let's say a column only has the values of: A, B, C.

Can I instead have a drop down to select one or more of those values? Or perhaps a radio group?

Thanks!

**Comment by jgodi** [comment]
Yes, the filter can be a dropdown as well. When setting your column up, you can set options for what is they can filter on.

```
{ title: 'Status', name: 'status', filtering: true, options: ['Test', 'Another'] }
```

**Comment by BRS999** [comment]
:+1:
