### ISSUE TITLE
[Tooltip/Table] Filter is cutoff when the table has no matching records.

### ISSUE THREAD

**Issue by BRS999** [bullhorn/novo-elements#532]
I'm submitting a BUG REPORT.

What is the current behavior?

Currently, the tooltip for the filter option on a table column is cutoff when there are no matching records.

Steps:

1. In a novo table, filter until there are no matching records.
2. Mouse over a filter icon and observe the tooltip being cutoff.

I was able to reproduce this issue here: http://bullhorn.github.io/novo-elements/#/table.

What is the expected behavior?

Tooltip will not be cutoff.

Please tell us about your environment:

- Angular version: 4+
- Browser: Chrome 60

![novo popover](https://user-images.githubusercontent.com/6516437/29421128-10a135ba-8342-11e7-9150-365671d3c6d8.jpg)

**Comment by jgodi** [comment]
Yep! Turns out we have some bad CSS overrides in our app so we masked this issue. Will fix it soon! Thanks!

**Comment by jgodi** [comment]
Fixed via https://github.com/bullhorn/novo-elements/commit/1359cc773a395c2250633a12a717a6db676efde7.
