### ISSUE TITLE
[Question] Setting initial values in a static form

### ISSUE THREAD

**Issue by BRS999** [bullhorn/novo-elements#539]
Hello,

I want to set some initial values in a static novo elements form. 

I see that formUtils has a method to set the initial values. 

Let's say I have a form with first name, last name, and telephone. 

How do I make the proper association to the form controls?

Do I do something like `{ key: 'phone', value : 555-555-555}`? 

Or do I need additional values?

Thanks!

**Comment by MagicAardvark** [comment]
Hi Ben, 

Thanks for reaching out.

you can set the values on a static form using the `setInitialValues` method as you rightfully stated. after which you pass in an object of key/value pairs such as
`formUtils.setInitialValues(this.form, { phone: '555-555-555', firstName: 'Bobby', lastName: 'Flay' });`

You can see this in action if you look at the code for our forms demo page 
`https://github.com/bullhorn/novo-elements/blob/master/demo/pages/elements/form/FormDemo.ts`

Hope this helps.

Thanks
Kyle.

**Comment by BRS999** [comment]
Thanks again Kyle!

**Comment by jgodi** [comment]
Also, with static forms when you are setting up the control object you can just set `value` on that object as well!

**Comment by BRS999** [comment]
Ah that makes sense. Thanks Joshua!

**Comment by jgodi** [comment]
@BRS999 No problem! Just out of curiosity what are you using NovoElements for? That way we can take that into consideration as we make improvements and new elements!

**Comment by BRS999** [comment]
I'm working on an Angular app to extend Bullhorn. I'm accustomed to Bootstrap I've had to switch gears with Novo. But with your help, the documentation, and examples I'm getting the hang of it.

**Comment by jgodi** [comment]
Awesome to hear! Thanks for using the library!
