### ISSUE TITLE
[Question] Switching form controls based on type

### ISSUE THREAD

**Issue by BRS999** [bullhorn/novo-elements#548]
Hello again!

I have a form that needs to switch one of its controls based on entity type. The form control is a picker control that needs to be switched out when the entity type changes.

I've created a static form but I'm not sure if this is the right approach. Should I convert this form into a dynamic form? And then change the control on init?

Thanks again.

**Comment by jgodi** [comment]
Do you know the entity type before the Control is displayed on the screen?

If so, you can still use the static form just throw a loading into the page while you create the form. Then create the form objects with the entity in mind.

If the entity can change after the form is displayed, then you can change it via our FieldInteractionAPI (which works on static forms). That is documented here: http://bullhorn.github.io/novo-elements/#/field-interactions

Let me know if you still have questions after this. Thanks!

**Comment by BRS999** [comment]
All good now. Thanks again for your help Joshua.
