### ISSUE TITLE
[Question] Setting up AppBridge

### ISSUE THREAD

**Issue by BRS999** [bullhorn/novo-elements#551]
Hello!

I'm in the process of integrating app bridge but I get an error.

I've wrapped appbridge in a service as follows:

```
import { Injectable } from '@angular/core';
import { AppBridge } from 'novo-elements';
import { environment } from '../../environments/environment';

@Injectable()
export class AppBridgeService {

  private bridge: AppBridge;

  private registered = false;

  constructor() {
    this.bridge = new AppBridge(environment.appBridgeConfig.title);
    this.bridge.tracing = true;
    this.register();
  }

  execute(execute: (bridge: AppBridge) => void) {
    if (this.registered) {
      execute(this.bridge);
    } else {
      const interval = setInterval(() => {
        if (this.registered) {
          clearInterval(interval);

          execute(this.bridge);
        }
      }, 500);
    }
  }

  private register() {
    this.bridge.register(environment.appBridgeConfig).then( () => {
      this.registered = true;
    }, () => {
      setTimeout(() => {
        this.register();
      }, 500);
    });
  }

}
```

I've added the following const to the environment file:
```
export const environment = {
  production: false,
  appBridgeConfig: {
    title: 'dev',
    url: 'http://localhost:4200/',
    color: 'blue'
  }
```
And then I've injected the appbridge service into a component.

When I load the application I get this error - `ERROR ReferenceError: postRobot is not defined`.

Did I miss something?

Thanks!

**Comment by jgodi** [comment]
You need ```<script src="//cdn.rawgit.com/krakenjs/post-robot/7da06445/dist/post-robot.js"></script>``` inside your html file.

**Comment by BRS999** [comment]
Ok that fixed it. So now I'm getting an error `[dev] "register - FAILED - (no parent)" Error: Window does not have a parent`. I'm working locally. I'm not too familiar with CDPM. Is there some additional setup needed to fire off a request to BH?

**Comment by jgodi** [comment]
The AppBridge will only work when you are inside of Bullhorn. So when you have your integration loaded as a CustomTab or CustomCard. The AppBridge registers with BH when it loads and then allows you to use it.

You will not be able to use it outside of this, so for development mode you will just want to mock all your calls before they hit AppBridge or load your integration in BH.

**Comment by BRS999** [comment]
Thanks for all your help. You're the best!

**Comment by jgodi** [comment]
@bvkimball just added a DevMode for AppBridge! It only works for HTTP calls and it requires you to be logged into Novo in another browser, but its a good step!

https://github.com/bullhorn/novo-elements/pull/560

**Comment by BRS999** [comment]
Even better! I'll have to check it out. Thanks for the update.

**Comment by BRS999** [comment]
Couple clarifying questions.

When you say novo do you mean something like cls20.bullhornstaffing.com?

Also, when you say another browser do you mean a separate browser? For instance, if I'm developing in chrome I have to have BH open in FF?

Thanks!

**Comment by BRS999** [comment]
Actually I have a few more questions! 

I've read through the sample projects and I believe I've set things up correctly.

I've added the appBridgeFactory to a module as such.

```
let bridge: AppBridge;
export function appBridgeFactory(http: Http): AppBridge {
    if (!bridge) {
        if ( environment.production ) {
            bridge = new AppBridge('Test prod');
        } else {
            bridge = new DevAppBridge('Test dev', http);
        }
        bridge.register();
        bridge.tracing = true;
    }
    return bridge;
}
```
I've also included it under providers: 

```
      provide: AppBridge,
      useFactory:  appBridgeFactory,
      deps: [ Http ]
```
I've also `--disable-host-check` on start.

Now when I try to get an entity I get a 404.

`http://localhost:4200/undefined/entity/Lead/6109827 404 (Not Found)`

This is the method I use to get the entity.

```
this.bridge.httpGET('entity/Lead/6109827')
    .then( 
      x => console.log(x), 
      error => console.log('error', error));
```
Did I miss something with the setup? This may be unrelated but I don't see this cookie `UlEncodedIdentity` when I'm logged into BH.

Thanks again!

**Comment by jgodi** [comment]
Sorry for the delayed response, we had Bullhorn Live going on. I will try my best to get to this comment today and help you out!

**Comment by BRS999** [comment]
Hey any update on this?

**Comment by jgodi** [comment]
You need to login to Novo. This will create and store a cookie that is used for authentication.

Then you local development, you need to modify your host file to add the entry:

```
127.0.0.1     localhost local.bullhornstaffing.com
```

Then just go to `local.bullhornstaffing.com:4200` this will allow that cookie to be accessed and set the base REST URL.

**Comment by jgodi** [comment]
If you are not on Novo, you might need to contact support to enabled Universal Login. That login will give you the appropriate cookies. 

If that is not possible, then we can try to come up with something else.

**Comment by jgodi** [comment]
Also, also, you just open the login to Novo in one Chrome tab and develop in another. It needs to be in the same browser window to share cookies.

**Comment by BRS999** [comment]
Thanks for the response! Regarding novo, would the end users of our extension also need to be logged into novo? Or is this to utilize dev mode? I want to clarify and make sure our end users can utilize the extension and make calls via appbridge.

**Comment by jgodi** [comment]
Yes, it is only for DEV mode of AppBridge. We have code in the DEV one only that: 

```
let cookie = this.getCookie('UlEncodedIdentity');
        if (cookie && cookie.length) {
            let identity = JSON.parse(decodeURIComponent(cookie));
            let endpoints = identity.sessions.reduce((obj, session) => {
                obj[session.name] = session.value.endpoint;
                return obj;
            }, {});
            this.baseURL = endpoints.rest;
        } 
```

looks at that specific cookie. For production mode, this is inherited automatically. So you users can be Novo or S-Release. 

Just out of curiosity, but sort of integration are you building for your users?

**Comment by BRS999** [comment]
Awesome. Thanks for the quick reply. We're creating a table using novo-elements that consolidates several entities into one view.

**Comment by BRS999** [comment]
Hey so I'm now in Novo. I've modified my host file. I see a list of cookies from .bullhornstaffing.com but `'UlEncodedIdentity'` is not one of them. When I try to execute an app bridge HTTPGET I get a 404 and see the following url - 

`http://local.bullhornstaffing.com:4200/undefined/search/Task?fields=id,subject,type,isCompleted,dateBegin&count=20&query=isDeleted:0%20AND%20isCompleted:false%20AND%20owner.id:6129577&sort=dateBegin,-dateAdded 4`

Any suggestions?

**Comment by BRS999** [comment]
You know on a whim I tried adding -ssl true along with --disable-host-check when I serve my app and it seems to be working! Thanks again for your help.

**Comment by Goldlion-star** [comment]
Hi, I am setting up AppBridge. But I have an issue like you.
Now I'm getting an error [dev] "register - FAILED - (no parent)" Error: Window does not have a parent.
I am happy if you help me with this issue.
Thanks.
