### ISSUE TITLE
[General Question] Why is the "Slider" element named "Slides" in documentation?

### ISSUE THREAD

**Issue by SchnWalter** [bullhorn/novo-elements#553]
##### **I'm submitting a...**

- [ ] Bug Report
- [ ] Feature Request
- [x] General Question

##### **What is the current behavior?**

The "Slides" element from the documentation that seems to be a "slideshow" (used for presenting images and text in a sequence), powered by a class named "Slider" and this is misleading. Two different words are used for the same component.

##### **What is the expected behavior?**

**TL;DR:** The component should have consistent naming, and maybe the "slider" component should be deprecated in favor of a "slides" component that provides the same functionality. I'm suggesting this because, a "Slider" seems to be a GUI element that is used to select a numerical value or a range, like a volume slider or a value range selector.

And a quick search for "GUI Slider" on a search engine reveals a lot of screenshots of GUI widgets from old OSes and libraries like jQuery UI or Material Design and all use the same naming convention for range selectors not image galleries. See:

* https://en.wikipedia.org/wiki/Slider_(computing)
* http://jqueryui.com/slider/#range
* https://material.angular.io/components/slider/overview

And I also went and search through filed patents and found that the "Slider" widget has been used to select numeric values for quite some time now:

* https://www.google.com/patents/US5877758 - Microsoft, 1996
* https://www.google.com/patents/US7765491 - Apple, 2005

And looking at related queries on G Trends, you can see that a "slideshow" is usually associated with "pictures" or "images" and the term "slider" isn't, at least not in the top 25 related queries.

**Comment by jgodi** [comment]
This is the name that we came up with during our development of this component library. We are currently underway of making these elements more performant and easier to use, so we will definitely take this under consideration.

Thank you!
