### ISSUE TITLE
[Question] IE 11 Support

### ISSUE THREAD

**Issue by BRS999** [bullhorn/novo-elements#555]
Hello again!

Does novo elements support IE 11? 

I'm noticing some odd behavior with a novo table and IE 11.

Thanks!

**Comment by jgodi** [comment]
We are currently working on fixing up this library for cross-browser support. IE11 is underway right now. I will keep you posted!

**Comment by jgodi** [comment]
@BRS999 How has IE11 been for you? We have seen our application work pretty good in IE11. Just want to check in with you before closing this out.

**Comment by BRS999** [comment]
Thanks for checking in. I've noticed a few peculiarities with tables and IE 11. Take a look here:
http://bullhorn.github.io/novo-elements/#/table

![image](https://user-images.githubusercontent.com/6516437/33079257-27cc62d0-cea3-11e7-92fc-adcd141f472c.png)

**Comment by jgodi** [comment]
👍  I will keep this open and comb through! Thanks!
