### ISSUE TITLE
[Question] Using Novo Modals to Confirm an Action

### ISSUE THREAD

**Issue by BRS999** [bullhorn/novo-elements#556]
Hello again!

I want to use a novo modal to confirm a user's action.

After a user accepts, I want to perform additional actions.

I see that you can pass in a result into the `this.modalRef.close(true);`.

However, I'm not sure how to access that result from the component that is calling the modal.

Any suggestions?

**Comment by jgodi** [comment]
When you open the modal you can "subscribe" to when the user closes the modal (and get the value of the data you pass to `.close()`) via:

```
this.modalService.open(MyModal).onClosed.then((result) => { // do something });
```

`result` will be whatever you pass into `.close()`. So in your example it will be `true`

**Comment by BRS999** [comment]
Ah that makes sense! Thanks again.
