### ISSUE TITLE
[Question] About AppBridge and User Context

### ISSUE THREAD

**Issue by BRS999** [bullhorn/novo-elements#567]
Hello!

Is there a way via app bridge to grab the user's context? I'd like to say get all the tasks assigned to the currently logged in user. Is this possible?

Thanks!

**Comment by jgodi** [comment]
Hmm, good question. We currently do not have this inside of AppBridge. I will add this to a ticket that I am working on and get that added.

What versions of Bullhorn are you looking to support with your application? S-Release and Novo?

**Comment by BRS999** [comment]
My understanding is we want to support S-Release for now.

**Comment by jgodi** [comment]
👍 I will keep this open until that is implemented. What is your timeline for this project? This will require a change inside of our CRM code-base which will have to go through our release process and that.

**Comment by BRS999** [comment]
Wow thanks again! We have at least a few more weeks of development.

**Comment by jgodi** [comment]
Sorry for the delayed response on this. If you are in Novo, this should be in the .11 Release and you can do this via:

`appBridge.requestData({ type })`

Where type can be `settings`, `entitlements` or `user`.

If you are trying to do this via S-Release, that won't be supported until .12. Also with the .12 Release, in Novo/S-Release you will be able to pass `all` and it will give you everything.
