### ISSUE TITLE
[Question] Adding a Note via AppBridge

### ISSUE THREAD

**Issue by BRS999** [bullhorn/novo-elements#571]
Hello,

I'm having trouble adding a note to an Opportunity and a referenced entity like a Lead.

The note is created for the Lead but not the Opportunity.  Here's an example of my request.

```
newNote = {
        action: action,
        comments: comments
        personReference: {
          id: data.opportunity.leadId
        },
        commentingPerson : {
          id: data.ownerId
        },
        opportunities: {
          id: data.EntityId
        }
}
```

When I execute the request, I get this warning `ATTEMPT_TO_SET_TO_MANY`.

Did I miss something?

Thanks in advance!

**Comment by jgodi** [comment]
Opportunities on there is a TOO_MANY field. The save object will have to be an array of IDs like:

`opportunities: [ { id: data.EntityId }]`

That should do it for you.

**Comment by jgodi** [comment]
Opportunities on there is a TOO_MANY field. The save object will have to be an array of IDs like:

`opportunities: [ { id: data.EntityId }]`

That should do it for you.

**Comment by BRS999** [comment]
Awesome!! That's working. Thanks again!
