### ISSUE TITLE
[Question] Filtering dates in a table

### ISSUE THREAD

**Issue by BRS999** [bullhorn/novo-elements#572]
Hello!

I'm having an issue with filtering dates in a table.

The sorting works for types like texts and links but not for my dates.

I've set `sorting: true, filtering: true` for my date.

I have dates for this current year but when I filter on dates for the past year the table displays no matching records.

![due date](https://user-images.githubusercontent.com/6516437/32616424-53078b26-c540-11e7-9878-529985d26946.jpg)

![no tasks](https://user-images.githubusercontent.com/6516437/32616436-59872a1a-c540-11e7-830b-bd244dd54da4.jpg)

Some information that may or may not be relevant. 

Chrome Version 62.0.3202.89
@angular versions ^4.4.6

Additionally, I'm not getting any console errors.

Any thoughts?

Thanks!

**Comment by jgodi** [comment]
Quick question, is the data that you are rendering in each cell a string or a date or number? 

I.E. 'Nov 19 2017' or DateObject or Number (representing the millis)

**Comment by BRS999** [comment]
Hello,

It should be a date. In the column options I've set the type to date. And the type I want to use is Date.

**Comment by BRS999** [comment]
Ah I found the issue. It was my bug. I needed to create a new Date() from the json value I received. It's working now. Thanks again!
