### ISSUE TITLE
[Question] Opening a tab via App Bridge

### ISSUE THREAD

**Issue by BRS999** [bullhorn/novo-elements#584]
Hello again!

I want to open a tab via App Bridge in Novo but I'm having some trouble. 

I want to open the notes tab. I've tried: Notes, note, and notes but it doesn't seem to be working for me.

Here's my code.

```
bridge.open({
        type: 'record',
        entityType: someType,
        entityId : someId,
        tab: one of the options above as a string
      }).then
```

Did I miss something? 

Thanks in advance.

**Comment by jgodi** [comment]
This will be supported in the upcoming .12 Release of Novo/S-Release. Was an oversight when initially implemented the AppBridge.Open call.

To know what tab you should be passing, you can load that tab in either Novo/S-Release and then right-click & "view frame source". The URL should end in the tab and that is what you will pass in the `tab` param.
