### ISSUE TITLE
[Question] Multi-selecting on novo table filter

### ISSUE THREAD

**Issue by BRS999** [bullhorn/novo-elements#587]
Hello again,

Is there a way to multi-select options from the novo table filter dropdown?

For instance, if I want to filter on two entity types?

Thanks in advance.

**Comment by jgodi** [comment]
You should be able to set `{multiple: true}` on the column config. Let me know if that doesn't work.

**Comment by BRS999** [comment]
Hello!

I tried that but wasn't able to get it to work.

I see a mention of multiple in Table.ts ` if (Array.isArray(column.filter) && column.multiple) {` but I don't see a multiple property.
