### ISSUE TITLE
[Question] About select values

### ISSUE THREAD

**Issue by BRS999** [bullhorn/novo-elements#593]
Hello again!

I'm using a select list with some value/label objects.

The select list has the values I want to use like `{value: 'A', label : 'A' } ` etc.

Some of the data I'm pulling into the form is old and part of an older dropdown. However, this old data shows up in the list new select list.

For instance, it will be like options `A,B,C, somebadvalueIdontwant`.

Is there a way to prevent this bad data from being added to the select list?

**Comment by jgodi** [comment]
Can you provide any code? 

The simplest solution that I can think of is before you are passing the `options` array into the control, you filter it down to the data you want?

**Comment by BRS999** [comment]
I surely can.

So I'm using a dynamic form.

Here's the form code.

```
    fields: [
        {
            label: 'Baconator',
            required: true,
            type: 'select',
            name: 'customText12',
            options: baconSelectList,
            sortOrder: 2
        },
```
And here's the list.

```
export const baconSelectList = [
    { value: '-1',  label: 'With Cheese' },
    { value: '0',  label: 'Double Patty' },
    { value: '1',  label: 'No onions' }
]
```

And here's what happens when some 'old' data that's not on the list is being set as the initial value.

![image](https://user-images.githubusercontent.com/6516437/33732059-2a996668-db53-11e7-9d99-f17b2c567487.png)

**Comment by BRS999** [comment]
Hey any update on this? Is this a bug or perhaps an issue with how I implemented the picker?

**Comment by charlesabarnes** [comment]
Heya, I have been taking a look at some older issues now, this behavior is currently expected.  I get the potential use case, but in case an errant change was made without a save and they wanted to undo that change then they have the option to do so.

I believe some other potential options would include using a different form control such as a picker.

Please let me know if you have any more questions
