### ISSUE TITLE
[NE3] Port: Utils

### ISSUE THREAD

**Issue by jgodi** [bullhorn/novo-elements#598]
- [ ] Port Over Code
- [ ] Added More Detailed Demos
- [ ] Optimize JS/SCSS (remove comments, fix duplicate code)
- [ ] 100% Unit Test Code Coverage
- [ ] Automation Written via Cypress
- [ ] Ensure Safari / Firefox support

**Comment by jgodi** [comment]
Ported over the initial Utils needed. There will be more to come as we port over more and more components.

https://github.com/bullhorn/novo-elements-3.0/commit/1aeefd2a5f2a3a9c268f699c14af68ff81d6318b
https://github.com/bullhorn/novo-elements-3.0/commit/337fbf442a56ff4b2fa46359b5c42b625a01efc9

**Comment by bvkimball** [comment]
A majority of these exist already

**Comment by bvkimball** [comment]
Canceled.
