### ISSUE TITLE
[NE3] Port: Dropdown

### ISSUE THREAD

**Issue by jgodi** [bullhorn/novo-elements#616]
- [x] Port Over Code
- [x] Added More Detailed Demos
- [x] Optimize JS/SCSS (remove comments, fix duplicate code)
- [x] 100% Unit Test Code Coverage
- [x] Automation Written via Cypress
- [ ] Ensure Safari / Firefox support

**Comment by bvkimball** [comment]
renamed to menu

**Comment by bvkimball** [comment]
Canceled.
