### ISSUE TITLE
[NE3] Port: DateTimePicker

### ISSUE THREAD

**Issue by jgodi** [bullhorn/novo-elements#618]
- [ ] Port Over Code
- [ ] Added More Detailed Demos
- [ ] Optimize JS/SCSS (remove comments, fix duplicate code)
- [ ] 100% Unit Test Code Coverage
- [ ] Automation Written via Cypress
- [ ] Ensure Safari / Firefox support

**Comment by jgodi** [comment]
Blocked until #619 and #601 are complete

**Comment by bvkimball** [comment]
Canceled.
