### ISSUE TITLE
[NE3] Port: CategoryDropdown

### ISSUE THREAD

**Issue by jgodi** [bullhorn/novo-elements#622]
- [ ] Port Over Code
- [ ] Added More Detailed Demos
- [ ] Optimize JS/SCSS (remove comments, fix duplicate code)
- [ ] 100% Unit Test Code Coverage
- [ ] Automation Written via Cypress
- [ ] Ensure Safari / Firefox support

**Comment by jgodi** [comment]
Is this used anywhere?

**Comment by bvkimball** [comment]
Canceled.
