### ISSUE TITLE
[Question] Services and Dynamic Forms

### ISSUE THREAD

**Issue by BRS999** [bullhorn/novo-elements#630]
Hello again!

I want to convert a static form into a dynamic form. 

I have a PickerControl that calls our API like this:

```
      {
        options: (str: string) => {
          return new Promise((resolve) => {
            this.apiService.getStrings(str).subscribe(list => {
              setTimeout(() => {
                resolve(list);
              }, 300);
            })
          });
        },
        format: '$string1 $string2'
      }
```

Is there a way to reuse this or adapt this call in a dynamic form?

**Comment by jgodi** [comment]
Yes, you can use FieldInteractions to update the picker control you want when the form loads.

Look at http://bullhorn.github.io/novo-elements/#/field-interactions

**Comment by BRS999** [comment]
Awesome, thanks again!
