### ISSUE TITLE
Compose Message Via AppBridge

### ISSUE THREAD

**Issue by BRS999** [bullhorn/novo-elements#652]
Hello again!

I'd like to open the compose message view via AppBridge. This would be the same as going to an entity, clicking on actions and then clicking on email.

Is this possible?

Thanks in advance.

**Comment by jgodi** [comment]
Hello! Currently that is *not* possible. This would require a change to the Novo code base to support opening things that aren't `records` or `fastadd`.

After that change you would open with the params:

```
type: 'actions',
action: 'compose-message',
data: { ... data to preload }
```

I can update this to go out with the `.3` release. Not sure when you would need it by.

**Comment by BRS999** [comment]
Hello Joshua,

Thank you for the quick response.

This is in the nice to have category. When do you expect the .3 release to go out?

**Comment by jgodi** [comment]
.3 is slated to be released in March. If I remember correctly your custom tab works in S-Release and Novo? The fix will have to be put into both for it to work properly.

You will most likely get the new Novo version first and depending on your SL and deploy cycles S-Release will follow.

**Comment by BRS999** [comment]
Yes, our app needs to work in both S-Release and Novo. Thanks again for the response. I will keep an eye on the progress of .3!

**Comment by jgodi** [comment]
Awesome, I will keep you updated!

**Comment by charlesabarnes** [comment]
Heya, 

I am going through a few old issues and noticed this hasn't been updated in a while.  I will be closing this out.  Please let me know if you need further assistance with this.
