### ISSUE TITLE
[Question] Completing a task via App Bridge in S-Release

### ISSUE THREAD

**Issue by BRS999** [bullhorn/novo-elements#679]
Hello again!

I'm having an issue with completing tasks via app bridge in S-Release. It's working perfectly in Novo.

Here's the bit of code for the task.

```
    const completeTask = {
      id: this.data.task.taskId,
      isCompleted: true,
      owner: {
        id: this.data.ownerId
      },
      description: "some description",
      dateCompleted: Date.parse(new Date().toLocaleString()),
    };
```
Here's the app bridge call.

```
bridge.httpPOST(`entity/Task/${completeTask.id}`, completeTask),
```

The request url is https://cls20.bullhornstaffing.com

Basically I want to provide the minimum amount of info to complete the task.

The request is successful. Here's the response.

```
{"changeType":"UPDATE",
"changedEntityType":"Task",
"changedEntityId":2462408,
"data":{
"recurrenceType":"",
"recurrenceStyle":"",
"recurrenceFrequency":0,
"recurrenceDayBits":0}
}
```
Any ideas?

Thanks in advance!

===

Update.

More info. So my usertype is IT aka admin. As a normal user, I cannot update the task. When I upgrade the usertype, I can complete tasks. Is there a way via app bridge for a user to complete their own tasks?

**Comment by jgodi** [comment]
With AppBridge it makes all calls through the currently logged in user, so whatever their rest endpoint is that is where the calls will go through.

What calls are you trying to make?

**Comment by BRS999** [comment]
Hello!

The issue we're having is completing tasks. Some users with certain usertypes can complete tasks while others cannot. I believe this is related to entitlements but I'm not sure which one. 

If you can point me in the right direction I'd greatly appreciate it!

**Comment by BRS999** [comment]
This was related to entitlements. Thanks again for your help!
