### ISSUE TITLE
[Question] Retaining filtering for a table after a data refresh

### ISSUE THREAD

**Issue by BRS999** [bullhorn/novo-elements#703]
Hello again!

Quick question. 

Is it currently possible to retain the filtering/sorting values for a table after a data refresh? 

For example, I have my table, I apply my sorting/filtering, I refresh the data and the updated table includes the new data already filtered/sorted?

Thanks in advance.

**Comment by jgodi** [comment]
Hey! What table are you using? <novo-table> or <novo-data-table>?

**Comment by rnitu** [comment]
Hello Joshua! We're using the basic table:

```
<novo-table [theme]="theme"
            [dataProvider]="basic.rows"
            [columns]="basic.columns"
            [config]="basic.config"
            rowIdentifier="name">
    <novo-table-header class="demo-custom-header">
        TEST :)
        <div>
            <button theme="secondary"
                    (click)="reload()">Reload Data</button>
            <button theme="secondary"
                    (click)="changeTheme()">Change Theme!</button>
        </div>
    </novo-table-header>
    <div classs="table-message"
         table-empty-message>
        <i class="bhi-search-question"></i> Custom Empty State Template! Click RELOAD to get Data!</div>
    <div classs="table-message"
         table-no-matching-records-message>
        <i class="bhi-search-question"></i> Custom No Matched Records</div>
</novo-table>
```

**Comment by jgodi** [comment]
Ah, if possible can you update to the new DataTable? We will be deprecating the old table very soon!

The new table is WAY WAY better. Much faster, easier to setup and has the ability to retain filters!

Let me know if you need any help!
