### ISSUE TITLE
Drop Dragula support in favor of ngx-smooth-dnd

### ISSUE THREAD

**Issue by bvkimball** [bullhorn/novo-elements#752]
Dragula hasn't been updated in over 2 years.  Maybe even remove DnD support in novo-elements all together.

for reference
https://kutlugsahin.github.io/ngx-smooth-dnd/

**Comment by charlesabarnes** [comment]
That library is now decently old.  How about using CDK drag and drop?  https://material.angular.io/cdk/drag-drop/examples

**Comment by michael-amaya-bh** [comment]
We have deprecated dragula and are looking into a replacement. Follow our [release notes](https://bullhorn.github.io/novo-elements/docs/#/home) for updates.
