### ISSUE TITLE
data-table details row template

### ISSUE THREAD

**Issue by rnitu** [bullhorn/novo-elements#771]
Having trouble adding details row. 

Seems like the 'expandedRow' template is hard coded with the text 'You did not provide an "expandedRow" template!'

I have also tried to add a column " type: 'expand' " with a template, and get the same result.

We're using the latest version of 'novo-elements'

HTML:
```
 <ng-template novoTemplate="expandedRow"
               let-row>
    Why look at that, you clicked the details!
  </ng-template>
```
Component:
```
  public sharedDisplayColumns = [
    'expand',
    'id',
    'Type',
    'Name',
    'Title',
    'Description',
    'Company',
    'DueDate',
    'priority'
  ];
```

Thank you!

**Comment by jgodi** [comment]
I will look at this right now. Thank you for reporting.

**Comment by jgodi** [comment]
@rnitu Just pushed a fix. You can use the snapshot version of the repo until we publish the next version of NovoElements out (~3 weeks). To do that you can change your `package.json` version to be:

```
"novo-elements": "bullhorn/novo-elements-snapshot",
```

Then, as we release you can change that back to a specific version. Let me know if you have any questions!

**Comment by rnitu** [comment]
@jgodi Thank you for your help! It's working now!
