### ISSUE TITLE
Able to land on disabled fields and edit using keyboard tab

### ISSUE THREAD

**Issue by Thall1982** [bullhorn/novo-elements#788]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)

##### **I'm submitting a...**

- [ ] Bug Report

##### **What is the current behavior?**

Using Field Validation API.disable(''fieldName') it correctly disables the field for clicking on but if using tab to work through the edit form it allows us to land on disabled fields and edit - this only applies for field types or pickers/dropdowns/radio - not freetext. 

##### **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

ensure script written against field as onInit trigger using API.disable()
whilst on the edit tab complete a field value before a disabled field
hit tab on the keyboard
the dropdown menu will then appear and you can choose another value and it will write back to the field
then click save
that new value will then write back ot the DB

##### **What is the expected behavior?**

not able to click on or tab to disabled fields and therefore not able to edit

##### **Please tell us about your environment:**

- Browser: <CHROME>

**Comment by jgodi** [comment]
Thank you for reporting this! I will investigate and get a fix going.
