### ISSUE TITLE
[Picker/Chips] - Extra margin/padding on bottom

### ISSUE THREAD

**Issue by jgodi** [bullhorn/novo-elements#80]
There is weird extra padding/margin on the picker/chips dropdown.

<img width="339" alt="screenshot 2016-06-26 08 18 08" src="https://cloud.githubusercontent.com/assets/870799/16362531/a13fdee2-3b76-11e6-95db-ad71b62296ec.png">

**Comment by krsween** [comment]
Closed by PR [109](https://github.com/bullhorn/novo-elements/pull/101).
