### ISSUE TITLE
[Data-Table] Get total number of rows after filter/search

### ISSUE THREAD

**Issue by rnitu** [bullhorn/novo-elements#802]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)

##### **I'm submitting a...**

- [ ] Bug Report
- [ ] Feature Request
- [ x ] General Question

Is there any way to get the total number of rows after we filter/search the table?

Tried to count the rows, but the number is not accurate when paginating. 

Thank You,
Robert

**Comment by rnitu** [comment]
table.dataSource.current gives us current page total, but does not account for page row overflow (if the filtered row count is more than total page limit).

**Comment by rnitu** [comment]
Following up on this issue. Thank you!

**Comment by jgodi** [comment]
Will look into this issue and the other data-table issues this week! Thanks!

**Comment by rnitu** [comment]
Appreciate it!
Robert Nitu | Director, Innovation and Development | 24 Seven
41 Madison Avenue, 37th Floor | New York, New York 10010 | www.24seventalent.com
Office: 212.966.4426 | Direct: 646.937.6997

[24 Seven]<www.24seventalent.com>
Find us online: Twitter<http://twitter.com/24Seventalent> | Facebook<http://www.facebook.com/pages/24-Seven/22164072443?ref=s> | LinkedIn<https://www.linkedin.com/company/17937>

Be sure to check out this week's Trending Top Talent.<https://www.24seventalent.com/en-us/talents/>
________________________________
This message contains information which may be confidential and privileged. Unless you are the addressee (or authorized to receive for the addressee), you may not use, copy, re-transmit, or disclose to anyone the message or any information contained in the message. If you have received the message in error, please advise the sender by reply e-mail @24seveninc.com, and delete the message. E-mail communication is highly susceptible to spoofing, spamming, and other tampering, some of which may be harmful to your computer. If you are concerned about the authenticity of the message or the source, please contact the sender directly.
________________________________

**Comment by rnitu** [comment]
Following up on this issue. Thank you!

**Comment by jgodi** [comment]
Looking at these today! Was up in London for Engage last week.

**Comment by rnitu** [comment]
Hello Joshua,

Yes, but the issue is that we cannot get the total dataset size after we filter. For instance, we filter the date column to get todays rows, we should be able to see how many rows are returned from the filter.

Regards,
Robert Nitu | Director, Innovation and Development | 24 Seven
41 Madison Avenue, 37th Floor | New York, New York 10010 | www.24seventalent.com
Office: 212.966.4426 | Direct: 646.937.6997

[24 Seven]<www.24seventalent.com>
Find us online: Twitter<http://twitter.com/24Seventalent> | Facebook<http://www.facebook.com/pages/24-Seven/22164072443?ref=s> | LinkedIn<https://www.linkedin.com/company/17937>

Be sure to check out this week's Trending Top Talent.<https://www.24seventalent.com/en-us/talents/>
________________________________
This message contains information which may be confidential and privileged. Unless you are the addressee (or authorized to receive for the addressee), you may not use, copy, re-transmit, or disclose to anyone the message or any information contained in the message. If you have received the message in error, please advise the sender by reply e-mail @24seveninc.com, and delete the message. E-mail communication is highly susceptible to spoofing, spamming, and other tampering, some of which may be harmful to your computer. If you are concerned about the authenticity of the message or the source, please contact the sender directly.
________________________________

**Comment by jgodi** [comment]
`table.dataSource.currentTotal` is what you want

**Comment by rnitu** [comment]
I tried that, and it gives us total like ‘table.dataSource.total’.

Thank You,
Robert Nitu | Director, Innovation and Development | 24 Seven
41 Madison Avenue, 37th Floor | New York, New York 10010 | www.24seventalent.com
Office: 212.966.4426 | Direct: 646.937.6997

[24 Seven]<www.24seventalent.com>
Find us online: Twitter<http://twitter.com/24Seventalent> | Facebook<http://www.facebook.com/pages/24-Seven/22164072443?ref=s> | LinkedIn<https://www.linkedin.com/company/17937>

Be sure to check out this week's Trending Top Talent.<https://www.24seventalent.com/en-us/talents/>
________________________________
This message contains information which may be confidential and privileged. Unless you are the addressee (or authorized to receive for the addressee), you may not use, copy, re-transmit, or disclose to anyone the message or any information contained in the message. If you have received the message in error, please advise the sender by reply e-mail @24seveninc.com, and delete the message. E-mail communication is highly susceptible to spoofing, spamming, and other tampering, some of which may be harmful to your computer. If you are concerned about the authenticity of the message or the source, please contact the sender directly.
________________________________

**Comment by jgodi** [comment]
I used it in the new demo: http://bullhorn.github.io/novo-elements/#/data-table. Notice that the total label gets updated as you filter a column.

**Comment by rnitu** [comment]
Perfect! It works in the new snapshot! Thank you so much, we’re all set!

…And welcome back!
Robert Nitu | Director, Innovation and Development | 24 Seven
41 Madison Avenue, 37th Floor | New York, New York 10010 | www.24seventalent.com
Office: 212.966.4426 | Direct: 646.937.6997

[24 Seven]<www.24seventalent.com>
Find us online: Twitter<http://twitter.com/24Seventalent> | Facebook<http://www.facebook.com/pages/24-Seven/22164072443?ref=s> | LinkedIn<https://www.linkedin.com/company/17937>

Be sure to check out this week's Trending Top Talent.<https://www.24seventalent.com/en-us/talents/>
________________________________
This message contains information which may be confidential and privileged. Unless you are the addressee (or authorized to receive for the addressee), you may not use, copy, re-transmit, or disclose to anyone the message or any information contained in the message. If you have received the message in error, please advise the sender by reply e-mail @24seveninc.com, and delete the message. E-mail communication is highly susceptible to spoofing, spamming, and other tampering, some of which may be harmful to your computer. If you are concerned about the authenticity of the message or the source, please contact the sender directly.
________________________________
