### ISSUE TITLE
[Data-Table] Pagination update on filter/search

### ISSUE THREAD

**Issue by rnitu** [bullhorn/novo-elements#803]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)

##### **I'm submitting a...**

- [ x ] Bug Report
- [x] Feature Request
- [ ] General Question

##### **What is the current behavior?**

When filtering/searching the page number does not update to account for new filtered row count, leaving empty pages.

##### **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Search or filter the table (ID column = 1) and click on last page. It will be empty

##### **What is the expected behavior?**

The page count should update when filtering/searching.

**Comment by jgodi** [comment]
Fixed. When using the static service the pagination should update properly.

You can use `bullhorn/novo-elements-snapshot` in your `package.json` version to use the new changes until I publish them out.
