### ISSUE TITLE
[Data-Table] Date filter get today

### ISSUE THREAD

**Issue by rnitu** [bullhorn/novo-elements#804]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)

##### **I'm submitting a...**

- [ X ] Bug Report
- [ ] Feature Request
- [ ] General Question

Date column filter cannot get today's rows only, when there are rows that start at 12AM next day present.

**My Component:**
```
 {
      id: 'DueDate', label: 'Due Date', type: 'date', sortable: true, template: 'DueDate', filterable: {
        type: 'date',
        allowCustomRange: true,
        options:
        [
          { label: 'Past 30 Days', min: -30, max: -2 },
          { label: 'Past 3 Days', min: -3, max: -2 },
          { label: 'Today', min: 0, max: 0 },
          { label: 'Tomorrow', min: 1, max: 0 },
          { label: 'Next 3 Days', min: 1, max: 2 },
          { label: 'Next 30 Days', min: 1, max: 29 },
        ],
      }, enabled: true
    },
```

Would it be possible to substitute '.startOfTomorrow()' with '.endOfToday()'? That way we can leave the Min/Max values out, and get today's rows. 

[(https://date-fns.org/v1.28.0/docs/endOfToday )]

**novo-elements/src/platform/elements/data-table/cell-headers/data-table-header-cell.component.ts:**
```
 public filterData(filter?: any): void {
    let actualFilter = filter;
    if (this.config.filterConfig.type === 'date' && filter) {
      this.activeDateFilter = filter.label || this.labels.customDateRange;
      if (filter.startDate && filter.endDate) {
        actualFilter = {
          min: dateFns.startOfDay(filter.startDate.date),
          max: dateFns.startOfDay(dateFns.addDays(dateFns.startOfDay(filter.endDate.date), 1)),
        };
      } else {
        actualFilter = {
          min: filter.min ? dateFns.addDays(dateFns.startOfToday(), filter.min) : dateFns.startOfToday(),
          max: filter.max ? dateFns.addDays(dateFns.startOfTomorrow(), filter.max) : dateFns.startOfTomorrow(),
        };
      }
    }
```

**Comment by jgodi** [comment]
Fixed, you can use `bullhorn/novo-elements-snapshot` in your package.json version to use the new changes until I publish them out.

**Comment by rnitu** [comment]
Thank you so much!!!
Robert Nitu | Director, Innovation and Development | 24 Seven
41 Madison Avenue, 37th Floor | New York, New York 10010 | www.24seventalent.com
Office: 212.966.4426 | Direct: 646.937.6997

[24 Seven]<www.24seventalent.com>
Find us online: Twitter<http://twitter.com/24Seventalent> | Facebook<http://www.facebook.com/pages/24-Seven/22164072443?ref=s> | LinkedIn<https://www.linkedin.com/company/17937>

Be sure to check out this week's Trending Top Talent.<https://www.24seventalent.com/en-us/talents/>
________________________________
This message contains information which may be confidential and privileged. Unless you are the addressee (or authorized to receive for the addressee), you may not use, copy, re-transmit, or disclose to anyone the message or any information contained in the message. If you have received the message in error, please advise the sender by reply e-mail @24seveninc.com, and delete the message. E-mail communication is highly susceptible to spoofing, spamming, and other tampering, some of which may be harmful to your computer. If you are concerned about the authenticity of the message or the source, please contact the sender directly.
________________________________
