### ISSUE TITLE
Issue with Display Tip feature

### ISSUE THREAD

**Issue by Thall1982** [bullhorn/novo-elements#826]
Hi, 

I'm adding a Display Tip as a field validation against three fields, having tested this in staging with no issues, it works perfectly every time, for some reason in our live environment it just wont display the tips below the fields - it randomly does it sometimes on one of them but so far it has not done it at all on the other 2 that i am testing against. 

script i am using is pretty straightforward, it is triggered via a on change trigger:
`
var TSA_Details = API.getActiveValue(); console.log(TSA_Details);
var TSA_Client = TSA_Details.clientCorporation.name; console.log('TSA_Client:',TSA_Client);
var TSA_email = TSA_Details.email; console.log('TSA_email:',TSA_email);
var TSA_FirstName = TSA_Details.firstName; console.log('TSA_FirstName:',TSA_FirstName);
var TSA_SecondName = TSA_Details.lastName; console.log('TSA_SecondName:',TSA_SecondName);
var TSA_Name = TSA_FirstName + ' ' + TSA_SecondName; console.log('TSA_Name:',TSA_Name);

API.displayTip(API.getActiveKey(), 'TSA 1 Details: \n Name: ' + TSA_Name + '\n Client: ' + TSA_Client + '\n Email: ' + TSA_email, 'info', true);
`
example of it working in staging is attached
![working example in staging](https://user-images.githubusercontent.com/42434254/46195333-fa7ee480-c2fb-11e8-83fc-715a74e3a264.png)

Any help would be greatly appreciated

**Comment by amrutha-rajiv** [comment]
Hello, 
Can you please clarify if you're seeing the logs in your live environment? OR do you see any errors in the developer console when the onChange event is triggered?

**Comment by Thall1982** [comment]
Hi, you can see the logs in the live environment and there are no errors shown either.

**Comment by Thall1982** [comment]
not that i am aware of, it should essentially be like for like in Staging and Live.

/version.txt - LIVE:
NNNNNNNN        NNNNNNNN
N:::::::N       N::::::N
N::::::::N      N::::::N
N:::::::::N     N::::::N
N::::::::::N    N::::::N   ooooooooooo vvvvvvv           vvvvvvv ooooooooooo
N:::::::::::N   N::::::N oo:::::::::::oov:::::v         v:::::voo:::::::::::oo
N:::::::N::::N  N::::::No:::::::::::::::ov:::::v       v:::::vo:::::::::::::::o
N::::::N N::::N N::::::No:::::ooooo:::::o v:::::v     v:::::v o:::::ooooo:::::o
N::::::N  N::::N:::::::No::::o     o::::o  v:::::v   v:::::v  o::::o     o::::o
N::::::N   N:::::::::::No::::o     o::::o   v:::::v v:::::v   o::::o     o::::o
N::::::N    N::::::::::No::::o     o::::o    v:::::v:::::v    o::::o     o::::o
N::::::N     N:::::::::No::::o     o::::o     v:::::::::v     o::::o     o::::o
N::::::N      N::::::::No:::::ooooo:::::o      v:::::::v      o:::::ooooo:::::o
N::::::N       N:::::::No:::::::::::::::o       v:::::v       o:::::::::::::::o
N::::::N        N::::::N oo:::::::::::oo         v:::v         oo:::::::::::oo
NNNNNNNN         NNNNNNN   ooooooooooo            vvv            ooooooooooo

Date: Tue, 18 Sep 2018 16:14:06 GMT

Package Version: 201809.2.0

Build Information:
  Jenkins Build: 1
  Branch: support/201809_fixes
  Commit: 4259003c
  Image: bullhorn-hub.artifactory.bullhorn.com/novo:4259003c

Dependency Information:
  Angular: 5.1.2
  NovoElements: 2.15.0
  BH-Elements: 2.3.7
  Chomsky: 2.1.14
  Chomsky-NG2: 2.2.0
  Taurus: 1.4.0
  Bullhorn-Types: 0.3.0

/version.txt - STAGING:
NNNNNNNN        NNNNNNNN
N:::::::N       N::::::N
N::::::::N      N::::::N
N:::::::::N     N::::::N
N::::::::::N    N::::::N   ooooooooooo vvvvvvv           vvvvvvv ooooooooooo
N:::::::::::N   N::::::N oo:::::::::::oov:::::v         v:::::voo:::::::::::oo
N:::::::N::::N  N::::::No:::::::::::::::ov:::::v       v:::::vo:::::::::::::::o
N::::::N N::::N N::::::No:::::ooooo:::::o v:::::v     v:::::v o:::::ooooo:::::o
N::::::N  N::::N:::::::No::::o     o::::o  v:::::v   v:::::v  o::::o     o::::o
N::::::N   N:::::::::::No::::o     o::::o   v:::::v v:::::v   o::::o     o::::o
N::::::N    N::::::::::No::::o     o::::o    v:::::v:::::v    o::::o     o::::o
N::::::N     N:::::::::No::::o     o::::o     v:::::::::v     o::::o     o::::o
N::::::N      N::::::::No:::::ooooo:::::o      v:::::::v      o:::::ooooo:::::o
N::::::N       N:::::::No:::::::::::::::o       v:::::v       o:::::::::::::::o
N::::::N        N::::::N oo:::::::::::oo         v:::v         oo:::::::::::oo
NNNNNNNN         NNNNNNN   ooooooooooo            vvv            ooooooooooo

Date: Wed, 26 Sep 2018 17:29:57 GMT

Package Version: 201810.1.0

Build Information:
  Jenkins Build: 29
  Branch: master
  Commit: 1b02490e
  Image: bullhorn-hub.artifactory.bullhorn.com/novo:1b02490e

Dependency Information:
  Angular: 5.1.2
  NovoElements: 2.17.0
  BH-Elements: 2.3.7
  Chomsky: 2.1.14
  Chomsky-NG2: 2.2.0
  Taurus: 1.5.1
  Bullhorn-Types: 0.3.0

**Comment by jgodi** [comment]
Thanks, I will take a look.

**Comment by Thall1982** [comment]
perfect, thanks for the help. Its strange that it loads the toast messages no problem but wont load the displayTip?

**Comment by Thall1982** [comment]
Hi, is there an update on this at all?

**Comment by amrutha-rajiv** [comment]
I'm unable to see the same issue happen on my test environment. It would be great if you can send us a screenshot of your fieldmap page for the field that this field interaction is configured for.

Thanks!

**Comment by Thall1982** [comment]
Morning, 

the call works fine in our staging environment too, it is only on our live system it does not. 

screen shot of the fields below it is happening on. 
![image](https://user-images.githubusercontent.com/42434254/46594869-78e24000-cacd-11e8-8821-9b6f93a9bc9c.png)

**Comment by amrutha-rajiv** [comment]
I tried reproducing this issue again and I'm not getting anywhere with it. I've reached out through my channels so that Bullhorn Support is aware of this issue you're seeing and if you can reach out to Support too, that would be great. 

Sorry we can't help more on this thread, hope you get to the bottom of this issue!
