### ISSUE TITLE
Value's label appears twice for some cases in demo page

### ISSUE THREAD

**Issue by jay-quach-tbx** [bullhorn/novo-elements#836]
## Expected Behavior
Label appears above value

## Actual Behavior
In demo page, what appears to happen is, for Customer Formatter and External Links section, there's label without any value underneath, besides a correct pair of value and label. See Screenshot below:
<img width="498" alt="screen shot 2018-10-22 at 9 51 10 am" src="https://user-images.githubusercontent.com/43962425/47296794-5bd76200-d5e1-11e8-8e9c-df6fe0bfe177.png">

**Comment by charlesabarnes** [comment]
http://bullhorn.github.io/novo-elements/#/form-controls/value  Looks like we are all set on this.
