### ISSUE TITLE
Extra Filters on Data Table filterable columns

### ISSUE THREAD

**Issue by nickle799** [bullhorn/novo-elements#854]
**Describe the solution you'd like**
We would like to add extra boolean filter(s) onto column filters in Novo-Data-Table.

**Will this feature require a breaking change?**
Does your feature request require breaking changes to existing functionality of current components or services?
- [ ] Yes
- [X] No
- [ ] Not sure

**Alternative solutions**
We could also add another column for filtering by archived

**Will this feature require a change to dependencies?**
No

**Additional context**
<img width="533" alt="screen shot 2018-11-08 at 9 06 15 am" src="https://user-images.githubusercontent.com/181508/48203535-c0125980-e335-11e8-9759-a46fa0b802ef.png">

**Comment by bvkimball** [comment]
We should add customCellHeaderTemplates here:
https://github.com/bullhorn/novo-elements/blob/master/projects/novo-elements/src/elements/data-table/data-table.component.ts#L86

probably be named columnName + 'header'
