### ISSUE TITLE
Data-Table: Allow for multiple filters

### ISSUE THREAD

**Issue by nickle799** [bullhorn/novo-elements#867]
**Describe the solution you'd like**
When using novo-data-tables, we want to have the ability to have multiple columns be filtered at once

**Will this feature require a breaking change?**
This would involve changing the novo-data-table-state.service to have filter be an array, and then handle this on the invididual header cells
- [X] Yes
- [ ] No
- [ ] Not sure

**Will this feature require a change to dependencies?**
No

**Comment by MichaelDill** [comment]
We have implemented this feature in merge https://github.com/bullhorn/novo-elements/pull/956
