### ISSUE TITLE
Allow for selecting multiple options selected (for an individual column) at once for a data-table

### ISSUE THREAD

**Issue by nickle799** [bullhorn/novo-elements#900]
**Describe the solution you'd like**

**Will this feature require a breaking change?**
Does your feature request require breaking changes to existing functionality of current components or services?
- [ ] Yes
- [ ] No
- [ ] Not sure

**Alternative solutions**
What alternative solutions have you considered for achieving the desired outcome?

**Will this feature require a change to dependencies?**
Please list any changes in dependencies or new open source packages or libraries that this feature depends on.

**Additional context**

**Comment by MichaelDill** [comment]
We have implemented this feature in the following merge: https://github.com/bullhorn/novo-elements/pull/956
