### ISSUE TITLE
[Address] - countryID is countryName causing failures

### ISSUE THREAD

**Issue by benFyre** [bullhorn/novo-elements#988]
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)

**Describe the bug**
When having an address fieldGroup the country selector populates two values `countryID` and `countryName`. Both of these are the same string value when the `countryID` should be a number.

This causes filtering states to fail as it calls the function `findByCountryId`, but passes it the name instead of an Id. (Possible related issue, when trying to use type ahead to search for country or state it always says no results found regardless of what you type)

**To Reproduce**
https://stackblitz.com/angular/bavapxejkqn?file=app%2Faddress-control-example.ts
1. Observe the countryId is 1 by default
2. Change the country selection on the top country section, observe that the countryID is now the countryName of what you just selected
3. Checking in the console shows the failures from attempting to filter

**Expected behavior**
1. CountryID should be the number that corresponds to the selected country and the state field should be filtered by the country selection
2. Typing into the search box should display only the countries that match the given string instead of no results

**Actual behavior**
1. State drop-down fails to populate any options after selecting a country (displays US states on default load, but selecting the United states makes it disappear) 
2. Searching by any string displays "No Results"

**Screenshots**
![image (1)](https://user-images.githubusercontent.com/26716150/59609834-250d0980-90e6-11e9-8ac5-d789852473c2.png)

![error](https://user-images.githubusercontent.com/26716150/59610543-9ef1c280-90e7-11e9-83d4-58ab51fbea75.PNG)

List filtering by nothing
![list](https://user-images.githubusercontent.com/26716150/59610761-03148680-90e8-11e9-86d5-8d6f1ea0cb6d.PNG)
List filtering by three letters causing the options to disappear 
![list2](https://user-images.githubusercontent.com/26716150/59610760-03148680-90e8-11e9-9713-ae8ac583ccac.PNG)

**Additional context**

**Comment by MichaelDill** [comment]
@benFyre Closing this out as the fix has been merged.
